[14.0][MIG] purchase_discount: Migration to 14.0
OCA/purchase-workflow pull request #1033
Opened 2020-11-27 10:42 UTC by Vanneri

Work in progress , no review

2020-12-25 08:48 UTC, kittiu commented
@Vanneri is this will a WIP?

By the way, I am seeing the commit history and looks like you are trying to fix the README.rst, which are not necessary. It will be auto generated out of readme fractions when merged.

Please see this guideline https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

Let me know once it is ready for further review. Thank you!

2020-12-28 06:40 UTC, Vanneri commented
> @Vanneri is this will a WIP?
> 
> By the way, I am seeing the commit history and looks like you are trying to fix the README.rst, which are not necessary. It will be auto generated out of readme fractions when merged.
> 
> Please see this guideline https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch
> 
> Please use pre-commit too.
> 
> Let me know once it is ready for further review. Thank you!

sure let me check

2020-12-28 13:43 UTC, Vanneri commented
@kittiu Please review

2021-01-15 12:38 UTC, Vanneri commented
@kittiu  @HviorForgeFlow

2021-01-19 04:43 UTC, kittiu commented on purchase_discount/tests/test_product_supplierinfo_discount.py
> +        self.assertEquals(
```suggestion
        self.assertEqual(
```
Warning from test.

2021-01-19 04:46 UTC, kittiu commented
Functional test seem OK.

But please, can you help make just 2 commit according to guideline. https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

It will help us see changes easily.

2021-01-19 09:21 UTC, Vanneri commented
> Functional test seem OK.
> 
> But please, can you help make just 2 commit according to guideline. https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch
> 
> It will help us see changes easily. Thanks!

2021-01-19 09:51 UTC, Vanneri commented
> Functional test seem OK.
> 
> But please, can you help make just 2 commit according to guideline. https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch
> 
> It will help us see changes easily. Thanks!

Yup done it.

2021-01-19 09:56 UTC, kittiu approved these changes
LGTM

2021-01-19 11:03 UTC, HviorForgeFlow requested changes
Functional review:
default_supplierinfo_discount is not propagated to Purchase Orders properly

2021-01-20 05:06 UTC, Vanneri commented
> Functional review:
> default_supplierinfo_discount is not propagated to Purchase Orders properly

can you suggest further changes ?, I didn't tried to change the existing functionality !

2021-01-20 05:25 UTC, HviorForgeFlow approved these changes
default_supplierinfo_discount works fine. I misunderstood the Readme

2021-01-20 05:39 UTC, HviorForgeFlow commented
/ocabot merge nubump

2021-01-20 07:35 UTC, HviorForgeFlow commented
/ocabot merge nobump

2021-01-20 09:02 UTC, merged