[13.0][IMP] purchase_order_secondary_unit: Less code. Use product_secondary _unit mixin model from product-attribute repository.
OCA/purchase-workflow pull request #1066
Opened 2021-01-12 09:59 UTC by sergio-teruel

cc @Tecnativa TT27363
Also in this commit set secondary_uom as default is the product has informed a default purchase secondary uom for purchases.
ping @carlosdauden @chienandalu

2021-01-12 10:56 UTC, pedrobaeza commented
Add the PR dependency.

2021-01-12 11:27 UTC, sergio-teruel commented
you mean in the PR comment??

2021-01-12 13:32 UTC, pedrobaeza commented
Yes, for knowing why it's red, with this format:
```
Depends on:

- [ ] OCA/product-atribute#XXX
```

2021-01-12 13:34 UTC, sergio-teruel commented
Ok.. ready!!!

2021-01-15 15:40 UTC, chienandalu requested changes
Tests are failing

2021-01-15 19:45 UTC, sergio-teruel commented
@chienandalu tests fixed

2021-01-18 06:27 UTC, chienandalu commented
Still failing

2021-01-18 11:41 UTC, sergio-teruel commented
@chienandalu sorry!! PR dependency added (https://github.com/OCA/product-attribute/pull/773)

2021-10-27 19:51 UTC, carlosdauden approved these changes

2021-10-27 20:39 UTC, pedrobaeza approved these changes

2021-10-27 20:39 UTC, pedrobaeza commented
/ocabot merge major

2022-01-19 07:23 UTC, pedrobaeza commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> +                    attrs="{'readonly': ['|',('state', 'in', ('done', 'cancel'))]}"
```suggestion
                    attrs="{'readonly': [('state', 'in', ('done', 'cancel'))]}"
```

2022-01-19 07:23 UTC, pedrobaeza commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> +                    domain="[('product_tmpl_id.product_variant_ids', 'in', product_id and [product_id] or [])]"
Is this domain accepted that way?

2022-01-20 08:23 UTC, sergio-teruel commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> +                    domain="[('product_tmpl_id.product_variant_ids', 'in', product_id and [product_id] or [])]"
Yes... It works!

2022-01-20 08:23 UTC, sergio-teruel commented
Changes done!!

2022-05-12 22:59 UTC, pedrobaeza commented
/ocabot merge major

2022-05-13 08:03 UTC, pedrobaeza commented
/ocabot merge major

2022-05-13 08:17 UTC, merged

2022-05-13 09:09 UTC, pedrobaeza commented
Cherry-picked to v14 at ef214d19706f15509f77abf047d1e1ea1487700b