[13.0][IMP] procurement_purchase_no_grouping: Add product_category in procured_purchase_grouping field
OCA/purchase-workflow pull request #1077
Opened 2021-01-21 07:28 UTC by victoralmau

Add product_category in `procured_purchase_grouping` field

Related to 12.0: https://github.com/OCA/purchase-workflow/pull/1052

@Tecnativa TT27393

2021-01-21 07:45 UTC, pedrobaeza commented on procurement_purchase_no_grouping/i18n/procurement_purchase_no_grouping.pot
> +<<<<<<< HEAD
Incorrect cherry-picking with conflicts

2021-01-21 07:46 UTC, pedrobaeza commented on procurement_purchase_no_grouping/readme/CONFIGURE.rst
> +=======
Why adding this?

2021-01-21 08:39 UTC, pedrobaeza approved these changes

2021-01-21 10:44 UTC, Tardo approved these changes
LGTM :+1: code review. Only a non-blocking comment

2021-01-21 10:44 UTC, Tardo commented on procurement_purchase_no_grouping/models/stock_rule.py
> +        elif values.get("grouping") == "order":
In the worst case, only take the value once
```suggestion
        grouping = values.get("grouping")
        if grouping == "product_category":
            if values.get("product_id"):
                product = self.env["product.product"].browse(values["product_id"])
                domain += (
                    ("order_line.product_id.categ_id", "=", product.categ_id.id),
                )
        elif grouping == "order":
```

2021-01-21 10:50 UTC, pedrobaeza commented on procurement_purchase_no_grouping/models/stock_rule.py
> +        elif values.get("grouping") == "order":
This barely optimizes, as both is an access to a variable or a value in a dictionary. There are microseconds of difference. It's no the same as caching other things in variables that requires a more complicated access (ORM fields for example), or for clearer code.

2021-02-02 11:28 UTC, victoralmau commented
Aplly PRs:
- [x] https://github.com/OCA/purchase-workflow/pull/1052 
- [x] https://github.com/OCA/purchase-workflow/pull/1080 
- [x] Adapt 13.0

Please @pedrobaeza and @Tardo, review it again.

2021-02-02 11:53 UTC, pedrobaeza requested changes
You have split commits, and it can make sense if you also separate pre-commit stuff. As is, the 13.0 adaptation commit doesn't make too much sense, as it mixes things that are not pure 13.0 changes, but formatting one. This also learns you to try to use in 12.0 already black syntax (specially quotes) for avoiding a lot of changes.

Being in this situation, I would squash the 3 commits into one.

2021-02-02 11:53 UTC, pedrobaeza commented on procurement_purchase_no_grouping/readme/CONFIGURE.rst
> +=======
This still continues here

2021-02-05 15:03 UTC, pedrobaeza approved these changes

2021-02-05 15:03 UTC, pedrobaeza commented
/ocabot merge major

2021-02-05 15:42 UTC, merged