[FIX] Add vendor for new line
OCA/purchase-workflow pull request #1082
Opened 2021-01-22 10:54 UTC by Lopsanz

If line.partner_id is not defined, unit price is catched from product instead of vendor pricelist.

2021-01-22 14:12 UTC, chienandalu reviewed
That field is a related one. I couldn't reproduce the fail. Do you have steps to reproduce?

2021-01-22 18:22 UTC, Lopsanz commented
Of course, @chienandalu 

1. Take a product with: Cost price: X and several vendor pricelists. Vendor 1: Y , vendor 2. Z ...
2. Make a purchase order to vendor 1 or 2.
3. Launch "Recommended products". The wizard looks fine... prices are right, but....
4. Validate and look at unit price that arrives to order line. 

Debugging this code I've seen that lines that come from the wizard haven't parnter_id yet when po_line._onchange_quantity() is called in action_accept procedure.

Perhaps this is not the perfect fix, but it's an easy fix lol!

2021-01-25 10:44 UTC, chienandalu approved these changes

2021-01-25 10:44 UTC, chienandalu commented
Ok :+1:

2021-01-25 10:47 UTC, pedrobaeza requested changes

2021-01-25 10:47 UTC, pedrobaeza commented on purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
> +            'partner_id': self.partner_id.id,
Always add a comment for conflicting things:
```suggestion
            # set this related field manually, as there's a glitch
            # in ORM that doesn't set its initial value
            'partner_id': self.partner_id.id,
```

2021-01-25 12:50 UTC, chienandalu approved these changes

2021-01-25 12:51 UTC, pedrobaeza commented
But better in only one commit :wink:

2021-01-25 15:46 UTC, marcelsavegnago approved these changes

2021-02-09 01:40 UTC, kittiu commented
@Lopsanz would you merge commits as suggested by @pedrobaeza then we can merge this, I think.

2021-02-12 19:42 UTC, Lopsanz commented
Only a commit, @pedrobaeza

2021-02-12 19:43 UTC, pedrobaeza approved these changes

2021-02-12 19:43 UTC, pedrobaeza commented
Great, thanks!

/ocabot merge patch

2021-02-12 20:45 UTC, merged