[ADD] 12.0 : new module purchase_no_rfq that remove request for quotation concept in purchase workflow
OCA/purchase-workflow pull request #1168
Opened 2021-04-30 11:42 UTC by legalsylvain

This module extends the odoo purchase module, to remove 'Request for Quotation' state, simplifying
the workflow for the ends users.

Once installed :

* The menu item 'Purchase > Purchase > Requests for Quotation' is hidden. A single menu item 'Purchase Order'
  is available

* The states names of the purchase order is altered. 'RFQ' is replaced by 'Draft' and 'RFQ sent' by 'Sent'.

* The colors in the tree view is correctly set to ``decoration-info`` for 'draft' and 'sent' orders.

![purchase_order_tree](https://user-images.githubusercontent.com/3407482/116690490-ba9fa280-a9b9-11eb-8a5d-3f8c542709cc.png)

* In the form view, all the RFQ names are removed or replaced by 'Purchase Order'.
  The module makes also the 'Print' button allways available and not only on 'draft' and 'sent' status.

* The option 'Print > Request For quotation' is also disabled.

![purchase_order_form](https://user-images.githubusercontent.com/3407482/116690507-c25f4700-a9b9-11eb-9059-411fd7da9411.png)

2021-04-30 12:51 UTC, quentinDupont approved these changes
Tested on clean Odoo and reviewed :heavy_check_mark:

2021-04-30 14:09 UTC, quentinDupont requested changes
Just a minor change in translation https://github.com/legalsylvain/purchase-workflow/pull/1

2021-04-30 14:28 UTC, quentinDupont approved these changes

2023-03-27 06:59 UTC, hparfr approved these changes
Can't test on runbot.

Code read, looks ok.

2023-03-27 06:59 UTC, hparfr commented on purchase_no_rfq/readme/DESCRIPTION.rst
> +the workflow for the ends users.
```suggestion
the workflow for the end users.
```

2023-03-27 07:27 UTC, bealdav approved these changes

2023-04-18 21:40 UTC, legalsylvain commented
hi @OCA/procurement-purchase-maintainers : some could merge this accepted PR ?

2023-04-19 07:06 UTC, HviorForgeFlow commented
/ocabot merge nobump

2023-04-19 07:59 UTC, merged