[14.0][MIG] purchase_reception_notify: Migration to 14.0
OCA/purchase-workflow pull request #1174
Opened 2021-05-10 23:21 UTC by daylinglez

@AaronHForgeFlow @JordiBForgeFlow could you please review?

2021-05-11 10:40 UTC, AaronHForgeFlow approved these changes
Functional on runbot :+1:

2021-05-18 03:17 UTC, daylinglez commented
@HviorForgeFlow could you review?

2021-05-18 11:47 UTC, HviorForgeFlow requested changes

2021-05-18 11:47 UTC, HviorForgeFlow commented on purchase_reception_notify/models/stock_picking.py
> +        super(StockPicking,self)._action_done()
Precommit failing due to a missing space, you could add the space or do this:
```suggestion
        super()._action_done()
```

2021-05-18 11:48 UTC, HviorForgeFlow commented on purchase_reception_notify/models/stock_picking.py
> +        super(StockPicking,self)._action_done()
Run pre-commit again! there is another issue here: https://github.com/OCA/purchase-workflow/pull/1174/checks?check_run_id=2607277868#step:4:105

2021-05-18 14:49 UTC, HviorForgeFlow approved these changes

2021-05-20 05:54 UTC, HviorForgeFlow commented
/ocabot merge nobump

2021-05-20 06:25 UTC, merged