[14.0] Add purchase_partner_incoterm
OCA/purchase-workflow pull request #1286
Opened 2021-10-22 07:30 UTC by sonhd91

2021-10-25 07:22 UTC, sebalix requested changes

2021-10-25 07:22 UTC, sebalix commented on purchase_incoterm/__manifest__.py
> +    'name': 'Purchase Incoterm',
I would rename the addon `purchase_partner_incoterm` to be inline with the existing [`sale_partner_incoterm`](https://github.com/OCA/sale-workflow/tree/14.0/sale_partner_incoterm).
+ Update the descriptions/user labels as well to be coherent:
```suggestion
    "name": "Default purchase incoterm per partner",
    "summary": "Set the supplier preferred incoterm on each purchase order",
```

2021-10-25 07:22 UTC, sebalix commented on purchase_incoterm/__manifest__.py
> +        'base',
```suggestion
```

2021-10-25 07:22 UTC, sebalix commented on purchase_incoterm/models/purchase_order.py
> +            self.incoterm_id = False
There is already a `onchange_partner_id` on `purchase.order`, better to re-use it and simplify the implementation:
```suggestion
    def onchange_partner_id(self):
        res = super().onchange_partner_id()
        self.incoterm_id = self.partner_id.purchase_incoterm_id
        return res
```

2021-10-25 07:22 UTC, sebalix commented on purchase_incoterm/models/res_partner.py
> +        string="Purchase Incoterm",
Use the same terms than `sale_partner_incoterm`:
```suggestion
        string="Default Purchase Incoterm",
        help="The default incoterm for new purchase orders for this supplier.",
```

2021-10-27 02:32 UTC, sonhd91 commented on purchase_incoterm/models/res_partner.py
> +        string="Purchase Incoterm",
Thanks for reivew, branch updated

2021-10-27 02:32 UTC, sonhd91 commented on purchase_incoterm/models/purchase_order.py
> +            self.incoterm_id = False
Thanks for reivew, branch updated

2021-10-27 02:32 UTC, sonhd91 commented on purchase_incoterm/__manifest__.py
> +    'name': 'Purchase Incoterm',
Thanks for reivew, branch updated

2021-10-27 07:38 UTC, TDu commented on purchase_incoterm/__manifest__.py
> +    'name': 'Purchase Incoterm',
I wonder it the name in the manifest should not be the name of the module without the underscore ?

2021-10-27 07:39 UTC, TDu commented
Renaming the module as proposed by @sebalix into `purchase_partner_incoterm` seems like a good idea

2021-10-27 15:18 UTC, sebalix commented
@sonhd91 could you rename the module `purchase_partner_incoterm`?

2021-10-28 02:42 UTC, sonhd91 commented
> @sonhd91 could you rename the module `purchase_partner_incoterm`?

module name changed, thanks

2021-10-28 06:22 UTC, TDu approved these changes

2021-10-28 08:45 UTC, sebalix approved these changes

2021-11-02 08:42 UTC, simahawk commented
/ocabot merge nobump

2021-11-02 09:51 UTC, merged