[FIX] purchase_discount: Fix undefined argument on purchase_discount: original function use move=False and inherited function just use move
OCA/purchase-workflow pull request #1362
Opened 2022-02-15 22:37 UTC by rolandojduartem

The original code caused the following error https://gist.github.com/rolandojduartem/64f4c0775d1eb11ff9c6bcfda02b94be at the moment to create a bill from a purchase order. This code fix that error. The original function is https://github.com/odoo/odoo/blob/14.0/addons/purchase/models/purchase.py#L1143
![purchase-wokflow_fix](https://user-images.githubusercontent.com/90422721/154160422-504b1e69-44d6-4c74-8c40-372a0d5a1e24.png)

2022-02-16 07:17 UTC, pedrobaeza reviewed
Thanks for the patch. Pleas sign the CLA.

2022-02-16 07:17 UTC, pedrobaeza commented on purchase_discount/models/purchase_order.py
>          vals = super(PurchaseOrderLine, self)._prepare_account_move_line(move)
```suggestion
        vals = super()._prepare_account_move_line(move=move)
```

2022-02-23 15:51 UTC, rolandojduartem commented
Hi, @luisg123v, could you review this pull request, please?

2022-02-23 15:52 UTC, pedrobaeza commented on purchase_discount/models/purchase_order.py
>          vals = super(PurchaseOrderLine, self)._prepare_account_move_line(move)
Can you attend this comment?

2022-02-23 21:42 UTC, pedrobaeza approved these changes

2022-02-23 21:42 UTC, pedrobaeza commented
Oh, there are conflicts.

2022-02-23 22:28 UTC, luisg123v requested changes
It seems the fix you're trying to submit was already performed one year ago on #1108.

2022-02-23 22:39 UTC, rolandojduartem commented
This pull request  will be closed because the issue was fixed one year ago.

2022-02-23 22:39 UTC, closed without merging