[14.0][ADD] purchase_order_vendor_products_only
OCA/purchase-workflow pull request #1415
Opened 2022-04-10 19:08 UTC by isserver1

Limit selection of the products in a PO to the ones available from the selected Venor

2022-04-12 15:40 UTC, elvise approved these changes
LGTM

2022-04-12 15:44 UTC, elvise commented
@OCA/community-maintainers take a look

2022-04-12 15:52 UTC, francesco-ooops approved these changes
Functional review ok

2022-04-14 07:29 UTC, HviorForgeFlow commented
/ocabot merge nobump

2022-04-14 07:34 UTC, HviorForgeFlow requested changes
Could you please do these changes:
- I would name it like `purchase_order_restrict_vendor_product` (Avoiding plurals in module name)
 - Then change commit description to [14.0][ADD] purchase_order_restrict_vendor_product
 - I think the PR needs a rebase or at least remove changes in setup/_metapackage

2022-04-14 08:13 UTC, simahawk requested changes
@isserver1 thanks for your contrib.
You should fix this by:
* rebasing on 14.0
* do not delete any exiting file
* cherry-pick your own commits
* rewrite your commits as `Add purchase_order_vendor_product` and `Add purchase_order_vendor_product_only`

If you prefer you can open another PR starting again from 14.0

2022-04-19 07:41 UTC, simahawk commented
```
2022-04-15 13:02:09,764 8874 INFO openerp_test odoo.modules.loading: Module purchase_picking_state: loading demo
2022-04-15 13:02:09,904 8874 INFO openerp_test unittest.suite: ======================================================================
2022-04-15 13:02:09,905 8874 ERROR openerp_test unittest.suite: ERROR: setUpClass (odoo.addons.purchase_picking_state.tests.test_purchase_picking_state.TestPurchasePickingState)
Traceback (most recent call last):
File "/home/travis/odoo-14.0/odoo/tests/common.py", line 173, in _handleClassSetUp
setUpClass()
File "/home/travis/odoo-14.0/addons/account/tests/common.py", line 27, in setUpClass
assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
```

2022-04-19 07:45 UTC, isserver1 commented
> ```
> 2022-04-15 13:02:09,764 8874 INFO openerp_test odoo.modules.loading: Module purchase_picking_state: loading demo
> 2022-04-15 13:02:09,904 8874 INFO openerp_test unittest.suite: ======================================================================
> 2022-04-15 13:02:09,905 8874 ERROR openerp_test unittest.suite: ERROR: setUpClass (odoo.addons.purchase_picking_state.tests.test_purchase_picking_state.TestPurchasePickingState)
> Traceback (most recent call last):
> File "/home/travis/odoo-14.0/odoo/tests/common.py", line 173, in _handleClassSetUp
> setUpClass()
> File "/home/travis/odoo-14.0/addons/account/tests/common.py", line 27, in setUpClass
> assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
> AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
> ```

Yes, I saw this. But cannot understand how is this connected with the module I add. Would appreciate your assistance

2022-04-19 09:31 UTC, simahawk requested changes

2022-04-19 09:31 UTC, simahawk commented on purchase_advance_payment/__manifest__.py
> +    "version": "14.0.1.0.1",
are you sure you've rebased properly? These changes should be here apparently.

2022-04-19 09:33 UTC, simahawk commented
> > ```
> > 2022-04-15 13:02:09,764 8874 INFO openerp_test odoo.modules.loading: Module purchase_picking_state: loading demo
> > 2022-04-15 13:02:09,904 8874 INFO openerp_test unittest.suite: ======================================================================
> > 2022-04-15 13:02:09,905 8874 ERROR openerp_test unittest.suite: ERROR: setUpClass (odoo.addons.purchase_picking_state.tests.test_purchase_picking_state.TestPurchasePickingState)
> > Traceback (most recent call last):
> > File "/home/travis/odoo-14.0/odoo/tests/common.py", line 173, in _handleClassSetUp
> > setUpClass()
> > File "/home/travis/odoo-14.0/addons/account/tests/common.py", line 27, in setUpClass
> > assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
> > AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
> > ```
> 
> Yes, I saw this. But cannot understand how is this connected with the module I add. Would appreciate your assistance

Seems to be a conflict between modules. As you see here https://github.com/OCA/purchase-workflow/blob/14.0/.travis.yml#L19 certain modules run their tests w/out others.
Your modules - in theory - are not adding any functional changes that might hinder tests but you pulled other changes that might cause it. Just wild guessing...

2022-04-19 11:17 UTC, closed without merging