15.0 mig purchase request department
OCA/purchase-workflow pull request #1424
Opened 2022-04-13 13:49 UTC by JoelZilli

2022-04-13 13:55 UTC, HviorForgeFlow commented
/ocabot migration purchase_request_department

2022-04-14 08:32 UTC, ajaniszewska-dev approved these changes

2022-04-18 17:43 UTC, sswapnesh requested changes

2022-04-18 17:43 UTC, sswapnesh commented on purchase_request_department/models/purchase_request.py
> +        employees = self.env.user.employee_ids
we should use `employee_id` field from user

https://github.com/odoo/odoo/blob/b49a23fdd83c139f19c22017667005de2dd8cc75/addons/hr/models/res_users.py#L83

2022-04-18 17:43 UTC, sswapnesh commented on purchase_request_department/models/purchase_request.py
> +            employees[0].department_id
Same  for`department_id`  https://github.com/odoo/odoo/blob/b49a23fdd83c139f19c22017667005de2dd8cc75/addons/hr/models/res_users.py#L92

2022-04-18 17:43 UTC, sswapnesh commented on purchase_request_department/models/purchase_request.py
> +        readonly=True,
related fields are readonly by default

2022-04-26 14:14 UTC, JoelZilli commented
@sswapnesh 
All changes done!

2022-10-19 05:57 UTC, TheerayutEncoder approved these changes
LGTM!!! :+1:

2022-10-19 15:31 UTC, sswapnesh approved these changes

2022-11-04 12:37 UTC, HviorForgeFlow commented
/ocabot merge nobump

2022-11-04 12:53 UTC, HviorForgeFlow commented
/ocabot merge nobump

2022-11-04 13:03 UTC, merged