Add purchase_lead_hour
OCA/purchase-workflow pull request #1484
Opened 2022-06-10 11:02 UTC by mmequignon

supersedes https://github.com/OCA/purchase-workflow/pull/1483

2022-06-14 11:47 UTC, ivantodorovich commented on purchase_lead_hour/models/product_supplierinfo.py
> +    def get_next_availability_date(self):
```suggestion
    def _get_next_availability_date(self):
```

This should be private.
In odoo, public methods are exposed through xmlrpc
rule of thumb is make everything private unless you really want this

2022-06-14 11:47 UTC, ivantodorovich commented on purchase_lead_hour/models/stock_orderpoint.py
> +        seller = fields.first(self.product_id._select_seller(quantity=None))
```suggestion
        seller = self.product_id._select_seller(quantity=None)
```

`_select_seller` never returns more than 1 record

2022-06-14 14:47 UTC, mmequignon commented
@ivantodorovich thanks Iván, I updated my pr

2022-06-14 14:53 UTC, ivantodorovich approved these changes

2022-06-15 15:18 UTC, sebalix requested changes

2022-06-15 15:18 UTC, sebalix commented on purchase_lead_hour/models/stock_orderpoint.py
> +        # available qty as of now + delay
But here you only use your new hook `_get_next_availability_date` to compute the forecasted qty, and the forecasted date will remain unchanged if we override it. That's a blocking issue.

`_get_product_context` was using `lead_days_date` (computed from today in `_compute_lead_days`).
As you are overriding this lead date only in `_get_product_context`, maybe you will get the right qty, but the `lead_days_date` is still returning the std date.

We need a hook in Odoo core to replace the call to `fields.Date.today()` in `_compute_lead_days` so you can put the date/datetime you want, so you'll get coherent regarding the lead date and the qty. Then your `_get_product_context` could be removed.

2022-07-04 13:55 UTC, grindtildeath commented on purchase_lead_hour/models/product_supplierinfo.py
> +    def _get_next_availability_date(self):
> The function name doesn't really match with its content

https://github.com/OCA/purchase-workflow/pull/1483#discussion_r893636953 :stuck_out_tongue_winking_eye:

2022-07-04 13:55 UTC, grindtildeath commented on purchase_lead_hour/models/stock_orderpoint.py
> +        # Since product.supplierinfo delay is now a float, we need to get the
This comment looks outdated.

2022-07-04 13:55 UTC, grindtildeath commented on purchase_lead_hour/models/stock_rule.py
> +        buy_rule.ensure_one()
Any reason to use `ensure_one` here, as it would raise an error if you have more than one buy rule?

Wouldn't it be cleaner to check if the "buy" rule is in the orderpoint's rule_ids in your override of `_get_product_context` instead?

2023-12-24 12:20 UTC, closed without merging