[IMP] purchase_request: make mail sending optional
OCA/purchase-workflow pull request #1544
Opened 2022-08-22 14:01 UTC by i-vyshnevska

2022-08-23 11:32 UTC, ajaniszewska-dev commented
can we update readme about this functionality?

2022-08-29 08:48 UTC, mmequignon approved these changes

2022-08-29 13:14 UTC, simahawk requested changes
pls document this new config in `readme/CONFIGURE.rst`

2022-09-12 13:28 UTC, HviorForgeFlow approved these changes

2022-09-12 13:28 UTC, HviorForgeFlow commented
@i-vyshnevska could you squash fixup commit? Thanks

2022-09-13 07:28 UTC, simahawk requested changes
Please squash when done.

2022-09-13 07:28 UTC, simahawk commented on purchase_request/readme/CONFIGURE.rst
> +Can be disabled in configuration settings.
```suggestion
When a delivery for purchase request is confirmed, a notification to followers is generated.
You can control this with the flag "Notify followers on request allocation" in stock general settings
```

2022-09-13 07:28 UTC, simahawk commented on purchase_request/views/res_config_settings.xml
> +                            Notify folowers on request allocation
```suggestion
                            Notify followers on request allocation
```

2022-09-13 08:19 UTC, HviorForgeFlow commented
/ocabot merge minor

2022-09-13 08:33 UTC, merged

2022-11-11 15:33 UTC, CasVissers-360ERP commented
@i-vyshnevska @HviorForgeFlow Is a forward port is this planned to v15? The current functionality is very strict? Lots of companies do not want this kind of automatic communication.