[14.0][AD] purchase_stock_vendor_bill_breakdown
OCA/purchase-workflow pull request #1593
Opened 2022-10-11 01:39 UTC by geomer198

2023-01-16 10:57 UTC, francesco-ooops approved these changes
functional ok!

this is the stock version of https://github.com/OCA/purchase-workflow/tree/14.0/purchase_vendor_bill_breakdown

2023-01-17 18:18 UTC, GabbasovDinar requested changes

2023-01-17 18:18 UTC, GabbasovDinar commented on purchase_stock_vendor_bill_breakdown/__manifest__.py
> +    "installable": True,
I understand that this module will be used for module compatibility (purchase_vendor_bill_breakdown and stock), maybe in this case would add the parameter "auto_install": True?

2023-01-17 18:18 UTC, GabbasovDinar commented on purchase_stock_vendor_bill_breakdown/models/purchase_order_line.py
> +            line.component_ids._update_qty(line.qty_received - line.last_qty_invoiced)
Please, don't update the field of another model in a method that is not intended for this purpose, this method is only needed to compute the `qty_received` field. Maybe you could use the `def _write` method in your case?

2023-01-18 20:01 UTC, geomer198 commented on purchase_stock_vendor_bill_breakdown/__manifest__.py
> +    "installable": True,
Resolved

2023-01-30 17:17 UTC, GabbasovDinar approved these changes
Code LGTM! Thanks

2023-01-30 17:18 UTC, GabbasovDinar commented
@geomer198 please, squash commits

2023-01-31 08:59 UTC, francesco-ooops commented
@OCA/procurement-purchase-maintainers this is the stock version of https://github.com/OCA/purchase-workflow/tree/14.0/purchase_vendor_bill_breakdown

do you think it's good for merge? both functional and code review have been done

2023-01-31 10:11 UTC, HviorForgeFlow commented
/ocabot merge nobump

2023-01-31 10:34 UTC, merged