[15.0][MIG] purchase_request_to_requisition
OCA/purchase-workflow pull request #1639
Opened 2022-11-17 10:05 UTC by Saran440

Reformatted:
- core odoo split module `purchase_requisition_stock` - https://github.com/odoo/odoo/commit/826f927a1ed54f6e2468e8f3b8649c1b7cfdf04b. So, we change depend `purchase_requisition` to `purchase_requisition_stock`
- change `<openerp>` to `<odoo>`
- move `id` before `name`

2022-11-22 08:14 UTC, gbrito-erpopen requested changes

2022-11-22 08:14 UTC, ghost commented on purchase_request_to_requisition/models/purchase_request.py
> +        )
```suggestion
        action = self.env["ir.actions.act_window"]._for_xml_id(
            "purchase_requisition.action_purchase_requisition"
        )
```

this is safer to use

2022-11-22 08:14 UTC, ghost commented on purchase_request_to_requisition/models/purchase_request.py
> +                )
```suggestion
        if self.requisition_lines:
            raise UserError(
                _("You cannot delete a record that refers to purchase lines!")
            )
```

2022-11-22 08:14 UTC, ghost commented on purchase_request_to_requisition/models/purchase_request.py
> +            rec.is_editable = False
```suggestion
        editable_records = self.filtered(lambda p: p in self and p.requisition_lines):
        editable_records.write({"is_editable": False})
```
You can make the write at once

2022-11-22 08:14 UTC, ghost commented on purchase_request_to_requisition/models/purchase_request.py
> +            action["res_id"] = requisitions.id
This will give an error if there is no requisition available. 
Would it be a good idea to check if the len(requisitions) == 1

2022-11-22 08:14 UTC, ghost commented on purchase_request_to_requisition/models/purchase_requisition.py
> +        )
Some thing as above, use the method ._for_xml_id

2022-11-22 08:14 UTC, ghost commented on purchase_request_to_requisition/models/purchase_requisition.py
> +        elif requests:
check if len of requests == 1 ?

2022-11-22 08:14 UTC, gbrito-erpopen commented on purchase_request_to_requisition/models/purchase_requisition.py
> +        domain = [("id", "in", request_line_ids)]
```suggestion
        domain = [("id", "in", self.purchase_request_lines.ids)]
```

2022-11-22 08:58 UTC, Saran440 commented on purchase_request_to_requisition/models/purchase_request.py
> +                )
this function should change to `if self.filtered("requisition_lines"):` for make sure case multi line.

what do you think @gbrito-erpopen ?

2022-11-22 09:40 UTC, Saran440 commented
@gbrito-erpopen fixed. thank you for you review

2022-11-22 09:46 UTC, gbrito-erpopen approved these changes

2023-01-13 06:59 UTC, ps-tubtim approved these changes
LGTM.

2023-02-08 10:03 UTC, kittiu commented
/ocabot merge nobump

2023-02-22 05:09 UTC, kittiu commented
/ocabot merge nobump

2023-02-22 09:22 UTC, merged