[15.0][FIX][purchase_discount] discount are readonly when invoice state is fully billed
OCA/purchase-workflow pull request #1822
Opened 2023-03-27 17:24 UTC by ernesto-garcia-tecnativa

2023-03-27 17:31 UTC, pedrobaeza commented
Check CI

2023-03-27 20:36 UTC, carlosdauden requested changes

2023-03-27 20:36 UTC, carlosdauden commented on purchase_discount/views/purchase_discount_view.xml
> +                    attrs="{'readonly': [('parent.invoice_status', '=', 'invoiced')]}"
Why don't use same condition that price_unit:
https://github.com/odoo/odoo/blob/51b693fa294ac3ee28cf55164bd14afa0d92a216/addons/purchase/views/purchase_views.xml#L252


```suggestion
                    attrs="{'readonly': [('qty_invoiced', '!=', 0)]}"
```

2023-03-31 18:58 UTC, carlosdauden approved these changes

2023-03-31 19:08 UTC, pedrobaeza approved these changes
/ocabot merge minor

2023-03-31 19:18 UTC, merged