[16.0][mig] purchase_blanket_order: Migration to 16.0
OCA/purchase-workflow pull request #1908
Opened 2023-06-08 05:51 UTC by dsolanki-initos

2023-10-20 11:58 UTC, SergiCForgeFlow commented
@dsolanki-initos Are you still working on this PR? If so, could you add this commit please [#2048](https://github.com/OCA/purchase-workflow/pull/2048)

2024-01-15 10:19 UTC, JordiBForgeFlow requested changes
Changes required.

2024-01-15 10:19 UTC, JordiBForgeFlow commented on purchase_blanket_order/views/purchase_blanket_order_views.xml
> +                                        groups="base.group_multi_company"
Does not make sense to add this group.

2024-01-15 10:19 UTC, JordiBForgeFlow commented on purchase_blanket_order/views/purchase_blanket_order_views.xml
> +                                        groups="base.group_multi_company"
Does not make sense to add this group.

2024-01-15 10:19 UTC, JordiBForgeFlow commented on purchase_blanket_order/views/purchase_blanket_order_views.xml
> +                    groups="base.group_multi_company"
Does not make sense to add

2024-01-15 10:19 UTC, JordiBForgeFlow commented on purchase_blanket_order/views/purchase_blanket_order_views.xml
> +                    groups="base.group_multi_company"
Does not make sense to add

2024-07-30 11:20 UTC, closed without merging