[FIX] purchase_discount: allow creating without product_tmpl_id
OCA/purchase-workflow pull request #2080
Opened 2023-11-02 12:22 UTC by yajo

Previous code was expecting a non-required field to be passed always. Now it's more resilient.

@moduon MT-1075 fwport-of https://github.com/OCA/purchase-workflow/pull/2079

2023-11-02 14:59 UTC, pedrobaeza commented on purchase_discount/tests/test_product_supplierinfo_discount.py
> +        cls.supplierinfo2["product_tmpl_id"] = cls.product.product_tmpl_id
Put a comment why this weird thing:

```suggestion
        # Assign it later this value for testing that the record
        # creation is not failing without this field
        cls.supplierinfo2.product_tmpl_id = cls.product.product_tmpl_id
```

2024-01-05 07:57 UTC, chienandalu requested changes
Take a look at https://github.com/OCA/purchase-workflow/pull/1780 :smile:

2024-06-14 07:36 UTC, yajo commented on purchase_discount/tests/test_product_supplierinfo_discount.py
> +        cls.supplierinfo2["product_tmpl_id"] = cls.product.product_tmpl_id
Thanks, fixed.

2024-06-14 09:51 UTC, yajo commented
> Take a look at #1780 😄

I see you included the fix from https://github.com/OCA/purchase-workflow/pull/2079/files#diff-d295e248990e2d37610dbda37a9460c56705b72005b4d1c7144af8c1c829a1c9 so I guess this PR is just a little test enhancement now.

2025-08-03 12:37 UTC, closed without merging