[14.0] [IMP] purchase_allowed_product: global setting and access rights
OCA/purchase-workflow pull request #2088
Opened 2023-11-08 11:12 UTC by renda-dev

- Add a global setting in purchase: "**Use only allowed products** by default"
    - When creating a new PO, field "**Use only allowed products**" is enabled by default
- Add a configuration in user: "Hide "**Use only allowed products**" in PO and invoice"
    - If this field is enabled in user, field "**Use only allowed products**" is not visible for this user.

2023-11-08 11:26 UTC, pedrobaeza commented
Your can do that setting a default, and the configuration settings have a direct option for that. Check other examples in Odoo core.

2023-11-08 12:20 UTC, renda-dev commented
Hi @pedrobaeza, that's awesome, thank you so much for letting me know :)

2023-11-08 13:31 UTC, francesco-ooops commented
@renda-dev there is something strange in settings as I don't see the setting and the "Purchase" section is duplicated

![image](https://github.com/OCA/purchase-workflow/assets/55489873/c9d2e612-05f2-4367-bd61-cea1bc779470)

2023-11-09 17:31 UTC, francesco-ooops approved these changes
Functional ok!

the error above is due to some other module (will try to find the culprit)

2023-11-09 21:06 UTC, geomer198 approved these changes
LGTM

2023-11-13 11:27 UTC, francesco-ooops commented
@pedrobaeza good for merge?

2023-11-13 11:33 UTC, pedrobaeza requested changes

2023-11-13 11:33 UTC, pedrobaeza commented on purchase_allowed_product/models/supplied_product_mixin.py
> +            self.use_only_supplied_product
With this, you are avoiding the option to disable the check automatically if previously was set. This is an undesired behavior.

2023-11-13 11:33 UTC, pedrobaeza commented on purchase_allowed_product/models/supplied_product_mixin.py
> +    def _default_hide_use_only_supplied_product(self):
Instead of doing this, just put the corresponding `groups` in the view.

2023-11-16 16:51 UTC, francesco-ooops approved these changes
Functionally still good, @pedrobaeza what do you say?

2023-11-21 09:16 UTC, francesco-ooops commented
@renda-dev rebase please

2023-11-21 09:54 UTC, francesco-ooops commented
@pedrobaeza shall we go? :)

2023-11-21 10:20 UTC, pedrobaeza approved these changes
/ocabot merge minor

2023-11-21 10:39 UTC, merged