[17.0][MIG] purchase_discount: Migration to 17.0
OCA/purchase-workflow pull request #2114
Opened 2023-12-08 21:50 UTC by ramiadavid

2023-12-09 09:31 UTC, pedrobaeza commented
AFAIK, this version includes discount natively in purchases.

2023-12-09 09:34 UTC, ramiadavid commented
@pedrobaeza Yes, but some features of the module are not the same, I have tried to leave only what is different

2023-12-11 08:02 UTC, pedrobaeza commented
Which features? I don't see any change in the readme files, and maybe the module name should be changed.

2023-12-11 13:45 UTC, ramiadavid commented
No, the readmes have not been modified yet, waiting to see what other people think about the future of this module.

While I was migrating it I saw that discounts on purchase orders are already included natively in Odoo 17 but there are functions of this module that are not.

- The default_supplierinfo_discount field and its respective functions are not in the standard version.

- Adding the discount to the supplierinfo when created from a purchase order is also not done by standard.

Basically I have left everything necessary so that the tests do not give errors.

I personally don't use those functions and I don't care whether they are there or not, but I don't know who has to decide what to do with the module.

The standard function works perfectly for me, but I need to have a solution with this module to be able to migrate the purchase_triple_discount module that depends on it and is the one I really need

2023-12-11 16:25 UTC, pedrobaeza commented
> Adding the discount to the supplierinfo when created from a purchase order is also not done by standard.

This can be considered a bug to be reported to Odoo.

2024-01-08 10:35 UTC, gurneyalex commented
/ocabot migration

2024-01-08 10:36 UTC, gurneyalex commented
/ocabot migration purchase_discount

2024-01-08 10:38 UTC, gurneyalex commented
@ramiadavid Please update the readme/* files

2024-01-08 10:39 UTC, pedrobaeza commented
As stated, I don't think this module should be continued as is.

2024-01-12 13:07 UTC, gurneyalex approved these changes

2024-01-12 15:15 UTC, pedrobaeza requested changes
This shouldn't be merged as is, as stated in the comments.

2024-01-12 15:44 UTC, ramiadavid commented
@pedrobaeza I know, what do you propose we do, I'm waiting for instructions, I don't think it's something I have to decide.

2024-12-10 13:50 UTC, BT-jmichaud commented
Integrated in standard, not needed anymore

2025-02-06 09:15 UTC, StefanRijnhart requested changes
I understand that there are small usability improvements that could have been preserved from the old purchase_discount module before Odoo implemented their own discount on supplier info and purchase order line models, but in all honesty, the current state of this PR does not make a good enough case for it, and after 14 months it's probably safe to say judging by the comments on here that there isn't enough interest in it.

2025-02-06 09:15 UTC, closed without merging