[17.0 []MIG] purchase_order_type
OCA/purchase-workflow pull request #2119
Opened 2023-12-17 16:56 UTC by celm1990

2023-12-17 17:54 UTC, pedrobaeza commented
/ocabot migration purchase_order_type

2023-12-27 11:48 UTC, dalonsod commented
Hello @celm1990 could you add fix commit added by #2136? Thanks!!

2023-12-27 19:34 UTC, celm1990 commented
> Hello @celm1990 could you add fix commit added by #2136? Thanks!!

@dalonsod  Cherry-pick done, please update your review

2023-12-28 09:59 UTC, dalonsod requested changes
Functional review :+1:  See comment

2023-12-28 09:59 UTC, dalonsod commented on purchase_order_type/views/view_purchase_order_type.xml
> +                <field name="active" invisible="True" />
This column is actually show. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0 for more details, but code should be modified like this (not tested):
```suggestion
                <field name="active" column_invisible="True" />
```

2023-12-28 13:10 UTC, celm1990 commented on purchase_order_type/views/view_purchase_order_type.xml
> +                <field name="active" invisible="True" />
Done, thanks for observation

2023-12-28 13:44 UTC, dalonsod approved these changes

2024-01-10 13:36 UTC, celm1990 commented
@OCA/procurement-purchase-maintainers, could you please help me review this PR and merge it if it is OK?

2024-01-19 12:17 UTC, celm1990 commented
@pedrobaeza could you help me with merge if it's OK

2024-01-19 12:25 UTC, pedrobaeza commented
It requires a review from a PSC.

2024-01-24 09:34 UTC, gurneyalex approved these changes

2024-01-24 09:35 UTC, gurneyalex commented
/ocabot merge nobump

2024-01-24 09:43 UTC, merged