[16.0][IMP] purchase_partner_selectable_option
OCA/purchase-workflow pull request #2157
Opened 2024-01-24 09:35 UTC by AungKoKoLin1997

This PR improves the process of choosing the default value for sale_selectable by utilizing a system parameter instead of hardcoding it.

@qrtl

2024-01-24 09:45 UTC, victoralmau requested changes

2024-01-24 09:45 UTC, victoralmau commented on purchase_partner_selectable_option/models/res_partner.py
> +        return True
```suggestion
        return True if param == "1" else False
```

2024-01-24 10:20 UTC, yostashiro commented on purchase_partner_selectable_option/readme/DESCRIPTION.rst
> +by adjusting the system parameter with the key 'purchase_partner_selectable_option.default_purchase_selectable'.
I suggest we put this in CONFIGURE.rst.

2024-01-24 10:31 UTC, yostashiro commented on purchase_partner_selectable_option/readme/DESCRIPTION.rst
> +by adjusting the system parameter with the key 'purchase_partner_selectable_option.default_purchase_selectable'.
I guess it's non-blocking as there seems to be no comment on this in the PR for the sales side https://github.com/OCA/sale-workflow/pull/2922.

2024-01-24 10:35 UTC, yostashiro commented on purchase_partner_selectable_option/readme/DESCRIPTION.rst
> +by adjusting the system parameter with the key 'purchase_partner_selectable_option.default_purchase_selectable'.
On second thought, we should clearly mention that the param should be `"0"` to make the default false.

2024-01-24 12:53 UTC, yostashiro approved these changes
Looks good. Thanks!

2024-01-24 12:54 UTC, victoralmau approved these changes

2024-02-06 17:47 UTC, rousseldenis approved these changes
Code review. Fair

2024-03-06 07:43 UTC, AungKoKoLin1997 commented
@OCA-purchase-workflow-maintainters
Can we get this PR merged?

2024-03-06 15:18 UTC, victoralmau approved these changes

2024-03-06 19:10 UTC, pedrobaeza commented
/ocabot migration purchase_partner_selectable_option
/ocabot merge nobump

2024-03-06 19:15 UTC, merged