[ADD] purchase_packaging_default
OCA/purchase-workflow pull request #2174
Opened 2024-02-20 12:35 UTC by santostelmo

Allows you to set a default packaging on the order line using the first packaging defined in the configuration of the respective product
Default packaging quantity is then set based on purchase order line quantity divided by product packaging quantity. 
Packaging quantity is rounded up as we sell it by units. For example: We won't sell 0.5 Boxes ot 1.5 Pallets.

2024-02-21 11:16 UTC, simahawk requested changes

2024-02-21 11:16 UTC, simahawk commented on purchase_packaging_default/models/purchase_order_line.py
> +            return package
```suggestion
        return fields.first(product_template.packaging_ids)
```

2024-02-21 11:16 UTC, simahawk commented on purchase_packaging_default/models/purchase_order_line.py
> +            return package
To be consistent w/ the sale module can we name this `_get_default_packaging`?

2024-02-21 11:16 UTC, simahawk commented on purchase_packaging_default/models/purchase_order_line.py
> +            return super(PurchaseOrderLine, self)._compute_product_packaging_id()
```suggestion
        _self = self
        if self.env.user.company_id.packaging_default_enabled:
            _self = _self.with_context(keep_product_packaging=True)
        return super(PurchaseOrderLine, _self)._compute_product_packaging_id()
```

2024-02-21 11:16 UTC, simahawk commented on purchase_packaging_default/models/purchase_order_line.py
> +        Super computes product_packaging_qty rounding it to packaging_uom.precision.
this is a comment

2024-02-21 11:16 UTC, simahawk commented on purchase_packaging_default/models/res_company.py
> +    packaging_default_enabled = fields.Boolean(
```suggestion
    purchase_packaging_default_enabled = fields.Boolean(
```

2024-02-21 13:22 UTC, santostelmo commented
@simahawk code updated

2024-02-22 07:54 UTC, simahawk approved these changes

2024-02-22 07:54 UTC, simahawk commented on purchase_packaging_default/models/purchase_order_line.py
> +        if self.env.user.company_id.purchase_packaging_default_enabled:
```suggestion
        if self.env.company.purchase_packaging_default_enabled:
```
non blocking of course

2024-03-26 10:11 UTC, cyrilmanuel approved these changes

2024-03-26 14:14 UTC, simahawk commented
/ocabot merge nobump

2024-03-26 16:58 UTC, simahawk commented
@santostelmo can you have a look at the failing test? https://github.com/OCA/purchase-workflow/actions/runs/8437473834/job/23107367001?pr=2174#step:8:966
Seems unrelated. You can open another PR to fix it.

2024-03-27 07:43 UTC, santostelmo commented
> @santostelmo can you have a look at the failing test? https://github.com/OCA/purchase-workflow/actions/runs/8437473834/job/23107367001?pr=2174#step:8:966 Seems unrelated. You can open another PR to fix it.

I tried to replicate on local without success 😔

2024-03-27 07:55 UTC, simahawk commented
I'll have a look

2024-04-16 08:30 UTC, santostelmo commented
@simahawk CI is green now

2024-04-16 08:34 UTC, cyrilmanuel approved these changes

2024-05-11 16:56 UTC, dreispt commented
/ocabot merge nobump

2024-05-11 17:05 UTC, merged