[ADD] purchase_order_confirm_partial: add module
OCA/purchase-workflow pull request #2175
Opened 2024-02-20 13:21 UTC by dmitriypaulov

2024-03-08 09:16 UTC, alexey-pelykh commented on purchase_order_confirm_partial/models/__init__.py
> +# Copyright (C) 2024 Cetmix OÜ
__init__ files normally don't have that

2024-03-08 09:16 UTC, alexey-pelykh commented on purchase_order_confirm_partial/models/purchase_order.py
> +            unconfirmed_lines |= line.copy(
Why are we collecting the lines if that recordset is not used?

2024-03-25 16:58 UTC, angelinaanaki requested changes
Please fix the error in the tests.

2024-03-25 16:58 UTC, angelinaanaki commented on purchase_order_confirm_partial/readme/USAGE.md
> +Internal note "Unconfirmed lines are saved in <UnconfirmedRFQNumber> will be posted in the chatter of the confirmed sales order.
```suggestion
Internal note "Unconfirmed lines are saved in <UnconfirmedRFQNumber> will be posted in the chatter of the confirmed purchase order.
```
Small typo.

2024-03-26 10:22 UTC, dmitriypaulov commented
> Please fix the error in the tests.

Those two failing checks are rebel modules tests, it's ok for them to fail

2024-03-26 14:33 UTC, angelinaanaki commented
> > Please fix the error in the tests.
> 
> Those two failing checks are rebel modules tests, it's ok for them to fail

Is the problem the same for https://github.com/OCA/purchase-workflow/actions/runs/8434575864/job/23098071417?pr=2175#step:8:1098, https://github.com/OCA/purchase-workflow/actions/runs/8434575864/job/23098071417?pr=2175#step:8:1116 and https://github.com/OCA/purchase-workflow/actions/runs/8434575864/job/23098071417?pr=2175#step:8:1121 ?

2024-04-16 14:30 UTC, angelinaanaki commented
There is an **Access Error** when RFQ is created:

Steps to reproduce:

- Goto Purchase -> Orders
- Click New
- Add vendor and products
- Click Save

Expected behavior:

- RFQ created

Current behavior:

**Access Error
Due to security restrictions, you are not allowed to access 'Purchase Order Line' (purchase.order.line) records. Contact your administrator to request access if necessary.**


I encountered the same error in another pull request as well: https://github.com/OCA/purchase-workflow/pull/2236. 
It appears the issue may be related to recent changes in the Odoo purchase module, specifically the purchase order line rule defined here: https://github.com/odoo/odoo/blob/16.0/addons/purchase/security/purchase_security.xml#L52. This change originates from this commit: https://github.com/odoo/odoo/commit/a04df5cb1411a14752ba7a4d6b3c4b7b4f1d6d44. Extending the domain with company_id = False allows creation to proceed without errors. However, when testing locally with a custom multi-company database, I encountered no access errors. 
It's possible these changes have disrupted the logic in another module within purchase-workflow, but I haven't yet identified which one.

2024-05-13 17:39 UTC, GabbasovDinar approved these changes

2024-07-17 16:21 UTC, alexey-pelykh commented
@dmitriypaulov yet the tests fail - how so?

Edit: I see that at least some errors originate from other module, yet the main branch is green - so this should be still investigated

2024-08-07 13:56 UTC, ivs-cetmix commented
> @dmitriypaulov yet the tests fail - how so?
> 
> Edit: I see that at least some errors originate from other module, yet the main branch is green - so this should be still investigated

@alexey-pelykh tests fail because of the rebel modules present in the repo

2024-08-08 13:11 UTC, alexey-pelykh commented
It seems that I can't do an end-to-end manual testing due to

```
Caused by: Error: Missing field string information for the field 'need_validation' from the 'purchase.order' model
```

Steps to reproduce:

1. Create Purchase Request and confirm it
2. Hit "Create RFQ" button
3. Observe the error

2025-11-09 12:32 UTC, closed without merging