[FIX] purchase_tag: update the _name_search args that caused an error
OCA/purchase-workflow pull request #2182
Opened 2024-02-25 22:47 UTC by nabilragab

please note that my organization @ragabnet is belonging to @nabilragab and i am the same contributor, i have another fork with another PR there for the default terms

2024-02-26 07:50 UTC, legalsylvain approved these changes
Commit message is not explicit. ( I don't understand what is the bug fixed here)
Otherwise lgtm.

2024-02-26 12:28 UTC, nabilragab commented
https://github.com/OCA/purchase-workflow/issues/2181

2024-04-24 12:48 UTC, astirpe approved these changes
Thank you for this fix.

2024-04-24 12:48 UTC, astirpe commented on purchase_tag/models/purchase_tag.py
>              name=name,
```suggestion
            name,
```

2024-04-24 12:48 UTC, astirpe commented on purchase_tag/models/purchase_tag.py
> +        self, name="", domain=None, operator="ilike", limit=100, order=None
Please use the same signature of method `_name_search()` as it is in standard odoo 17 :

`def _name_search(self, name, domain=None, operator='ilike', limit=None, order=None):`

See: https://github.com/odoo/odoo/blob/17.0/odoo/models.py#L1744

2024-05-27 09:03 UTC, HviorForgeFlow commented on purchase_tag/models/purchase_tag.py
> +        self, name="", domain=None, operator="ilike", limit=100, order=None
@nabilragab can you attend suggestions? Thanks! :)

2024-06-17 12:58 UTC, HviorForgeFlow requested changes
https://github.com/OCA/purchase-workflow/pull/2182#discussion_r1615740323

2024-09-26 15:02 UTC, codeagencybe commented
@legalsylvain 

Is there something stuck on this PR? I have a need for this module in a project. Anything I can help with?

2024-09-26 15:42 UTC, legalsylvain commented
Hi @codeagencybe . 
- in May 27, @HviorForgeFlow said that there was an error https://github.com/OCA/purchase-workflow/pull/2182#discussion_r1615740323 in the PR.
- since then, nothing changed.
- To go on, you can fork the @nabilragab branch, make the change, propose a PR, and so we can move forward.

Thanks !

2025-09-21 12:31 UTC, closed without merging