[IMP] purchase_request: split field 'Quantity in RFQ or PO' into purchased_qty and rfq_qty fields
OCA/purchase-workflow pull request #2213
Opened 2024-03-25 15:47 UTC by augusto-weiss

Features in this PR:

- Split field purchased_qty (Quantity in RFQ or PO) into purchased_qty and rfq_qty. And add it to views.

- Improve state of purchase request line to have more specific info. 
- Add to the compute method of the purchase request line state the dependence on quantities (i.e.: A purchase request line is not done if the purchase order quantities are less than de purchase request line quantities)

2024-04-04 17:18 UTC, augusto-weiss commented
@sonhd91 @gurneyalex Hello guys! Would you like to review this IMP pr ? I hope some feedback

2024-04-15 20:52 UTC, florenciafrigieri2 approved these changes
Functional test, is working ok.

2024-04-15 21:03 UTC, florenciafrigieri2 commented
Hi @pedrobaeza. Can you please check this PR? And also the 2237 which affects the same module.

Thanks in advance!

2024-04-17 19:23 UTC, pedrobaeza requested changes
You are modifying things that shouldn't be done in stable. Better that you add the split feature in a new module. The other option is to add migration scripts.

2025-10-12 12:30 UTC, closed without merging