[16.0][MIG] purchase_landed_cost: Migration to version 16.0
OCA/purchase-workflow pull request #2219
Opened 2024-04-01 14:45 UTC by carolinafernandez-tecnativa

- Standard migration from v13 to v16
- Squash administrative commits

@Tecnativa

@pilarvargas-tecnativa

2024-04-01 17:34 UTC, carolinafernandez-tecnativa commented
Checked CI and the problem is not from the module migrated.

2024-04-02 06:54 UTC, pedrobaeza commented
/ocabot migration purchase_landed_cost

2024-04-02 09:28 UTC, carolinafernandez-tecnativa commented
@pilarvargas-tecnativa @pedrobaeza rebased and ready for review

2024-04-08 11:34 UTC, pilarvargas-tecnativa approved these changes

2024-04-11 18:49 UTC, pedrobaeza requested changes
/ocabot migration purchase_landed_cost

2024-04-11 18:49 UTC, pedrobaeza commented on purchase_landed_cost/wizard/picking_import_wizard.py
> +                if all(x in moves for x in line.picking_id.move_line_ids):
```suggestion
                if all(x in moves for x in line.picking_id.move_ids):
```

2024-04-11 18:49 UTC, pedrobaeza commented on purchase_landed_cost/wizard/picking_import_wizard.py
> +        for move in self.mapped("pickings.move_line_ids"):
```suggestion
        for move in self.mapped("pickings.move_ids"):
```

and subsequent changes

2024-04-11 19:42 UTC, carolinafernandez-tecnativa commented on purchase_landed_cost/wizard/picking_import_wizard.py
> +        for move in self.mapped("pickings.move_line_ids"):
fix it, thanks!

2024-04-11 19:43 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2024-04-11 19:52 UTC, merged