[ADD] Add new module purchase_order_line_variant_description
OCA/purchase-workflow pull request #224
Opened 2016-04-28 07:19 UTC by hurrinico

This module is based on https://github.com/OCA/sale-workflow/tree/8.0/sale_order_line_variant_description and allow to use sale description on the purchase order lines as their names

2016-05-12 02:42 UTC, azmimr67 commented
Runbot tested :+1:

2016-05-12 10:24 UTC, eLBati commented on purchase_order_line_variant_description/__init__.py
> +# © 2015 Alex Comba - Agile Business Group
Alex or Nico?

2016-05-12 10:24 UTC, eLBati commented on purchase_order_line_variant_description/__openerp__.py
> +# © 2015 Nicola Malcontenti - Agile Business Group
2016?

2016-05-12 10:24 UTC, eLBati commented on purchase_order_line_variant_description/models/purchase_order_line.py
> +# © 2015 Nicola Malcontenti - Agile Business Group
2016?

2016-05-12 10:25 UTC, eLBati commented
Some remarks, then :+1:

2016-05-12 14:35 UTC, hurrinico commented
@eLBati Fixed

2017-06-26 07:54 UTC, tafaRU requested changes

2017-06-26 07:54 UTC, tafaRU commented on purchase_order_line_variant_description/__openerp__.py
> +        'sale_order_line_variant_description',
I think it's not needed so you can remove it.

2017-06-26 07:54 UTC, tafaRU commented on purchase_order_line_variant_description/models/purchase_order_line.py
> +            if product.variant_description_sale:
Shouldn't be `description_purchase`?

2017-06-26 07:54 UTC, tafaRU commented on purchase_order_line_variant_description/models/purchase_order_line.py
> +                res['value']['name'] = product.variant_description_sale
same as above.

2017-06-26 08:02 UTC, hurrinico commented on purchase_order_line_variant_description/models/purchase_order_line.py
> +                res['value']['name'] = product.variant_description_sale
This Module is based on sale_order_line_variant_description as description says, and use [this](https://github.com/OCA/sale-workflow/blob/8.0/sale_order_line_variant_description/models/product_product.py#L12) field.
I'm going to check travis error now

2018-03-23 12:26 UTC, gurneyalex commented
I just merged #529 which fixes the travis build of 8.0. Can you rebase?

2021-12-05 12:20 UTC, closed without merging