[17.0][MIG] purchase_order_no_zero_price
OCA/purchase-workflow pull request #2268
Opened 2024-05-06 13:46 UTC by mariobinhex

Standar migration

2024-05-08 11:38 UTC, Anxo82 approved these changes
LGTM :+1:

2024-05-08 14:35 UTC, ChristianSantamaria approved these changes
Tested LGTM :+1:

2024-05-15 01:09 UTC, HviorForgeFlow commented
@MarioLM-23 could you rename last commit (mig to v17) from 16 to 17. It is confusing. Thanks

2024-05-15 01:44 UTC, celm1990 approved these changes
LGTM

2024-05-27 03:35 UTC, HviorForgeFlow requested changes
Attend comment https://github.com/OCA/purchase-workflow/pull/2268#issuecomment-2111404052

2025-10-19 18:31 UTC, closed without merging