[17.0][MIG] purchase_order_secondary_unit: Migration to 17.0
OCA/purchase-workflow pull request #2319
Opened 2024-06-27 04:18 UTC by mmrondon

2024-07-23 23:04 UTC, mmrondon commented
Depending PR:
* [1560] [[17.0][MIG] product_secondary_unit product-attribute#1560](https://github.com/OCA/product-attribute/pull/1560)

2024-10-29 13:45 UTC, alan196 approved these changes
Functional Review 👍

2024-11-14 08:15 UTC, dalonsod requested changes
@mmrondon at last, this addon has been merged for v16 (see #2216) and has some improvements that come from v15 and aren't still available here. Could you take a look?

cc @sergio-teruel

2024-11-14 09:47 UTC, sergio-teruel commented
Please @mmrondon Can yo sure that all commits from older version are in your PR..?
Thanks

2024-11-25 09:59 UTC, dalonsod commented
Hello @mmrondon will you resume this PR soon? Thanks!

2024-11-26 11:42 UTC, peluko00 commented
Hi @mmrondon, can you squash commits into one please?

2024-11-28 10:58 UTC, dalonsod requested changes
@mmrondon could take a look at the comments, and the changes you've added in migration commit in general? It seems that you've preserved original migration commit files changes after you've update commit history, and some changes added in recently added commits have been lost.

2024-11-28 10:58 UTC, dalonsod commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> -                    optional="show"
Please don't remove this, as it was added in an recent commit, when updating commit history

2024-11-28 10:58 UTC, dalonsod commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> -                    optional="show"
The same as above

2024-11-28 10:58 UTC, dalonsod commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> +                />
It seems that some later changes have been lost in this commit:
- Move whole code to a `<t>` node.
- Improvements in `secondary_uom_id` domain added by https://github.com/OCA/purchase-workflow/pull/2216/commits/ee8f610f2fed6f4456a5b4c8c131883e511170ac

2024-11-28 10:58 UTC, dalonsod commented on purchase_order_secondary_unit/views/product_views.xml
> +                />
The same as below with `<t>` node

2024-11-28 22:08 UTC, mmrondon commented
hello @dalonsod sorry for that, already modified

2024-11-29 18:01 UTC, dalonsod requested changes
There are still some things to be fixed in commit history, please check

2024-11-29 18:01 UTC, dalonsod commented on purchase_order_secondary_unit/views/product_views.xml
> +                        groups="uom.group_uom"
This is redundant, the field is placed into a `<t>` that have already groups attribute

2024-11-29 18:01 UTC, dalonsod commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> +                        groups="uom.group_uom"
The same as above

2024-11-29 18:01 UTC, dalonsod commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> +                        groups="uom.group_uom"
The same as above

2024-11-29 18:01 UTC, dalonsod commented on purchase_order_secondary_unit/views/purchase_order_views.xml
> +                        domain="['|', ('product_id', '=', product_id),
`domain` definition is still the old one, changes added by https://github.com/OCA/purchase-workflow/commit/ee8f610f2fed6f4456a5b4c8c131883e511170ac are lost, please check diff at this point.

2024-12-09 08:47 UTC, dalonsod commented
Hello @mmrondon would you resume this PR and attend pending comments? Thanks!

2024-12-17 15:48 UTC, dalonsod commented
Superseded by #2492

2025-06-06 19:14 UTC, closed without merging