[17.0] [MIG] purchase_order_owner
OCA/purchase-workflow pull request #2347
Opened 2024-07-08 14:36 UTC by Deriman-Alonso

2024-10-17 18:09 UTC, StefanRijnhart requested changes
Please squash out the pandoc binary from the commit in which it was added.

2024-10-17 18:09 UTC, StefanRijnhart commented on purchase_order_owner/readme/DESCRIPTION.md
> +products in place of a client (you seprately issue an invoice to the
```suggestion
products on behalf of a client (you separately issue an invoice to the
```

2024-10-18 05:12 UTC, yostashiro commented on purchase_order_owner/models/purchase_order.py
> -        states=PurchaseOrder.READONLY_STATES,
A corresponding adjustment should be made in the view (`purchase_order_form`), adding `readonly="state in ['cancel', 'done', 'purchase']"`.

2024-10-18 05:12 UTC, yostashiro commented on purchase_order_owner/readme/CONTRIBUTORS.md
> +- [Binhex](hhttps://binhex.cloud/):
```suggestion
- [Binhex](https://binhex.cloud/):
```

2026-01-18 12:36 UTC, closed without merging