[17.0][MIG] purchase_order_line_menu
OCA/purchase-workflow pull request #2378
Opened 2024-07-31 08:52 UTC by ThiagoMForgeFlow

@ForgeFlow

2024-07-31 08:58 UTC, LoisRForgeFlow approved these changes
LGTM :+1:

2024-08-17 22:08 UTC, gbrito approved these changes

2024-08-20 07:54 UTC, HviorForgeFlow commented
/ocabot migration purchase_order_line_menu

2024-08-20 07:56 UTC, HviorForgeFlow requested changes

2024-08-20 07:56 UTC, HviorForgeFlow commented on .pre-commit-config.yaml
> +    rev: 400ffa99242c8b225ab4d34de78721a68b292a61
Not sure about this change.

2024-08-27 09:51 UTC, HviorForgeFlow commented
/ocabot migration purchase_order_line_menu

2024-08-27 10:11 UTC, HviorForgeFlow approved these changes

2024-08-27 10:16 UTC, HviorForgeFlow commented
/ocabot merge nobump

2024-08-27 10:22 UTC, merged