[MIG] purchase_fully_received: Migration to v16
OCA/purchase-workflow pull request #2408
Opened 2024-09-16 14:32 UTC by AaronHForgeFlow

@ForgeFlow

2024-09-17 14:37 UTC, rvalyi requested changes

2024-09-17 14:37 UTC, rvalyi commented on purchase_fully_received/readme/DESCRIPTION.rst
> +that the Purchase Order is fully Shipped.
the same kind of English mistakes as https://github.com/OCA/purchase-workflow/pull/2407 can be fixed here too...

2025-06-05 11:24 UTC, HviorForgeFlow approved these changes

2025-08-13 07:22 UTC, BhaveshHeliconia approved these changes
Functional review LGTM!

2025-08-13 10:34 UTC, HviorForgeFlow commented
/ocabot merge nobump

2025-08-13 10:47 UTC, merged