[17.0][MIG] purchase_order_line_sequence: Migration to 17.0
OCA/purchase-workflow pull request #2414
Opened 2024-09-23 14:27 UTC by StefanRijnhart

2025-06-06 08:27 UTC, AEstLo approved these changes
Code LGTM

2025-06-06 08:36 UTC, AEstLo commented
@rousseldenis do you think this can be merged?

2025-06-06 09:17 UTC, rousseldenis commented
> @rousseldenis do you think this can be merged?

@AEstLo The best is to attract other people to review

2025-06-06 09:17 UTC, rousseldenis commented
/ocabot migration purchase_order_line_sequence

2025-06-06 09:21 UTC, thomashaunschmid86 approved these changes

2025-06-06 10:42 UTC, bizzappdev approved these changes
Code LGTM

2025-06-06 11:17 UTC, AEstLo commented
> > @rousseldenis do you think this can be merged?
> 
> @AEstLo The best is to attract other people to review

Do you think it's good enough now? I'd like to start the migration to 18.0 when this is merged :)

2025-06-06 11:34 UTC, StefanRijnhart commented
@AEstLo you can start the 18.0 migration by taking this PR's branch in the git format patch command rather than 17.0
```
git remote add sr https://github.com/StefanRijnhart/purchase-workflow
git fetch sr 17.0-mig-purchase_order_line_sequence
git format-patch --keep-subject --stdout origin/18.0..sr/17.0-mig-purchase_order_line_sequence -- $module | git am -3 --keep
```

2025-06-06 13:47 UTC, HviorForgeFlow requested changes
Waiting dependency

https://github.com/OCA/stock-logistics-workflow/pull/1552

2025-06-06 15:28 UTC, AEstLo commented
> @AEstLo you can start the 18.0 migration by taking this PR's branch in the git format patch command rather than 17.0
> 
> ```
> git remote add sr https://github.com/StefanRijnhart/purchase-workflow
> git fetch sr 17.0-mig-purchase_order_line_sequence
> git format-patch --keep-subject --stdout origin/18.0..sr/17.0-mig-purchase_order_line_sequence -- $module | git am -3 --keep
> ```

Done: https://github.com/OCA/purchase-workflow/pull/2709

2025-06-10 07:20 UTC, AEstLo commented
> Waiting dependency
> 
> [OCA/stock-logistics-workflow#1552](https://github.com/OCA/stock-logistics-workflow/pull/1552)

@HviorForgeFlow this is merged now

2025-06-10 09:37 UTC, HviorForgeFlow approved these changes

2025-06-10 09:37 UTC, HviorForgeFlow commented
/ocabot merge nobump

2025-06-10 09:42 UTC, HviorForgeFlow requested changes

2025-06-10 09:42 UTC, HviorForgeFlow commented on test-requirements.txt
> +git+https://github.com/siemenv/stock-logistics-workflow@17.0-mig-stock_picking_line_sequence#subdirectory=stock_picking_line_sequence
Remove the dependency

2025-06-10 10:02 UTC, StefanRijnhart commented on test-requirements.txt
> +git+https://github.com/siemenv/stock-logistics-workflow@17.0-mig-stock_picking_line_sequence#subdirectory=stock_picking_line_sequence
Thanks! Removed dependency and rebased as well.

2025-06-10 11:16 UTC, HviorForgeFlow approved these changes

2025-06-10 11:16 UTC, HviorForgeFlow commented
/ocabot merge nobump

2025-06-10 11:26 UTC, merged