[MIG] purchase_tier_validation: Migration to 18.0
OCA/purchase-workflow pull request #2447
Opened 2024-11-04 04:28 UTC by Quan-nhm

2025-02-04 17:54 UTC, StefanRijnhart commented
/ocabot migration purchase_tier_validation

2025-02-04 18:25 UTC, StefanRijnhart requested changes
Can you add this test-requirements.txt to fix tests? https://github.com/OCA/purchase-workflow/blob/17.0/test-requirements.txt

2025-02-04 20:52 UTC, celm1990 commented
> Can you add this test-requirements.txt to fix tests? https://github.com/OCA/purchase-workflow/blob/17.0/test-requirements.txt

@StefanRijnhart  could you test this PR? It is more up-to-date https://github.com/OCA/purchase-workflow/pull/2447

2025-02-07 09:51 UTC, Quan-nhm commented
> Can you add this test-requirements.txt to fix tests? https://github.com/OCA/purchase-workflow/blob/17.0/test-requirements.txt

@StefanRijnhart , I got this error in the test. Do you know how to fix it?
![image](https://github.com/user-attachments/assets/789b07af-4416-4394-b808-b4e2cb16a7ed)

2025-02-07 09:57 UTC, StefanRijnhart commented
> > Can you add this test-requirements.txt to fix tests? https://github.com/OCA/purchase-workflow/blob/17.0/test-requirements.txt
> 
> @StefanRijnhart , I got this error in the test. Do you know how to fix it?

You added a file test-requirements.txt in the module directory but it needs to go into the root of the repo.

2025-02-07 10:02 UTC, StefanRijnhart commented
Can you get rid of the merge commit?

2025-02-07 10:02 UTC, Quan-nhm commented
> > > Can you add this test-requirements.txt to fix tests? https://github.com/OCA/purchase-workflow/blob/17.0/test-requirements.txt
> > 
> > 
> > @StefanRijnhart , I got this error in the test. Do you know how to fix it?
> 
> You added a file test-requirements.txt in the module directory but it needs to go into the root of the repo.

Thank you, I just found it that I put it in wrong place. I just fixed it.

2025-02-07 11:18 UTC, Quan-nhm commented
> Can you get rid of the merge commit?

@StefanRijnhart is this ok now?

2025-02-07 11:35 UTC, StefanRijnhart approved these changes
Thank you!

2025-02-12 03:38 UTC, celm1990 approved these changes
LGTM

2025-02-12 07:19 UTC, pedrobaeza commented
/ocabot migration purchase_tier_validation
/ocabot merge nobump

2025-02-12 07:25 UTC, merged