[18][MIG] purchase_request_tier_validation: Migration to 18
OCA/purchase-workflow pull request #2482
Opened 2024-12-12 20:09 UTC by Ricardo-MC

Depends on:

- [ ] https://github.com/OCA/server-ux/pull/966

supersedes  https://github.com/OCA/purchase-workflow/pull/2448

2025-01-30 13:24 UTC, rjaraspearhead approved these changes
LGTM 👍

2025-02-04 19:11 UTC, celm1990 requested changes
Please rebase the branch and remove the last commit, as PR https://github.com/OCA/server-ux/pull/992 has been merged, thanks

2025-02-07 22:37 UTC, celm1990 approved these changes
Tested, LGTM
@bosd @pedrobaeza @StefanRijnhart Could you please review this?, thanks in advance!

2025-02-07 23:12 UTC, pedrobaeza commented
/ocabot merge nobump

2025-02-07 23:18 UTC, merged