[18.0][MIG] purchase_cancel_reason: Migration to 18.0
OCA/purchase-workflow pull request #2484
Opened 2024-12-13 10:43 UTC by HeliconiaSolutions

2024-12-17 09:15 UTC, sebalix approved these changes
LG, proposing small improvements but not blocking

2024-12-17 09:15 UTC, sebalix commented on purchase_cancel_reason/tests/test_purchase_cancel_reason.py
> +class TestPurchaseCancelReason(TransactionCase):
We could inherit from `BaseCommon` class to disable tracking on all records created in tests.

2024-12-17 09:15 UTC, sebalix commented on purchase_cancel_reason/tests/test_purchase_cancel_reason.py
> +        super().setUp()
Small improvement, but as there is only one test this won't change anything here, so not blocking.
```suggestion
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
```

2024-12-19 05:14 UTC, HeliconiaSolutions commented
@sebalix , Thank you for your insightful comment, which has helped improve the code.

2024-12-19 07:38 UTC, StefanRijnhart requested changes
Thanks! I did a functional test. The spacing looks off on a cancelled purchase order. It seems to say

> Cancellation reason:Service no longer needed

A space would be nice, to make it say

> Cancellation reason: Service no longer needed

Then again, I'm not fond of this unconventional way of displaying what is really a regular field. Would you consider just showing the field, under the condition that it has a value, for instance under `Vendor Reference`?


![image](https://github.com/user-attachments/assets/309a672c-38f3-42fb-9515-e50c5364b410)

2024-12-19 07:39 UTC, StefanRijnhart commented
/ocabot migration purchase_cancel_order

2024-12-19 12:48 UTC, HeliconiaSolutions commented
@StefanRijnhart , Thank you for your insightful comment, which has helped improve the code.

2024-12-19 13:06 UTC, StefanRijnhart reviewed
Thanks for the update, but you can just make this a simple `<field name="cancel_reason_id" />`. No need for inline layout in this part of the form. That way, you can get rid of the layout tweak distinction between debug and non-debug mode (although it's well caught, and in other circumstances would be a sophisticated solution).

2024-12-20 16:16 UTC, sheragar reviewed
LGTM - Functional Review 👍
It has been verified that purchase orders can be canceled individually, with a cancellation reason correctly assigned within the order. However, when canceling multiple purchase orders simultaneously, the option to include a cancellation reason is not available.
Could we add functionality in this view to optionally include a reason when canceling? This would enhance the traceability and flexibility of the process.

2024-12-20 18:09 UTC, StefanRijnhart reviewed
Ah yes, that's right! Odoo 18 supports action buttons defined in list views as well, and `button_cancel` is added to two of those list views in the purchase module, e.g. https://github.com/odoo/odoo/blob/18.0/addons/purchase/views/purchase_views.xml#L596-L600. They would have to be replaced by this module's `action_purchase_order_cancel` as well.

2024-12-24 07:42 UTC, HeliconiaSolutions commented
@StefanRijnhart , @sheragar , Thanks for the suggestion to improve traceability! It was a great idea, and it helped streamline the process. I’ve fixed the issue and pushed the changes.

2025-01-05 12:37 UTC, StefanRijnhart approved these changes
Very nice, thanks!

2025-01-06 21:12 UTC, HviorForgeFlow commented
/ocabot merge nobump

2025-01-06 21:18 UTC, merged