[18.0][MIG] purchase_reception_status
OCA/purchase-workflow pull request #2501
Opened 2024-12-30 08:17 UTC by astirpe

2025-04-04 08:32 UTC, AaronHForgeFlow reviewed
I agree to keep with this module, I agree with this comment https://github.com/OCA/purchase-workflow/pull/1831#issuecomment-1548924543 

I did a functional review and it LGTM

2025-04-04 08:32 UTC, AaronHForgeFlow commented on purchase_reception_status/__manifest__.py
> +    "version": "18.0.1.0.1",
```suggestion
    "version": "18.0.1.0.0",
```

2025-04-28 08:42 UTC, bizzappdev commented
@astirpe We have prepared the Test Cases PR: https://github.com/astirpe/purchase-workflow/pull/1/ to increase the coverage, as there were no test cases for this module.

2025-05-01 08:43 UTC, TDu commented
@astirpe Thanks for the migration, could you apply the quick fix and those unit tests.

2025-05-06 08:02 UTC, astirpe commented on purchase_reception_status/__manifest__.py
> +    "version": "18.0.1.0.1",
Thank you!

2025-05-06 08:02 UTC, astirpe commented
@bizzappdev Thank you!

2025-05-06 08:58 UTC, AaronHForgeFlow approved these changes
Functional ok!

2025-05-13 08:52 UTC, twalter-c2c approved these changes
LGTM, thank you.

2025-05-13 09:56 UTC, sebalix commented
/ocabot migration purchase_reception_status

We need to merge first #2201 as this one is based on it. Once merged, 17.0 history should be refreshed there.

2025-05-21 08:16 UTC, LoisRForgeFlow requested changes
For me this cannot be merged as is, there is an unresolved discussion in v17 https://github.com/OCA/purchase-workflow/pull/2201#issuecomment-2897031126

2025-05-21 08:53 UTC, AaronHForgeFlow commented
so the proposal would be to overwrite the odoo standard compute field like this?

```
    receipt_status = fields.Selection([compute='_compute_good_receipt_status')

    @api.depends(
        "state", "force_received", "order_line.qty_received", "order_line.product_qty"
    )
    def _compute_good_receipt_status(self):
        prec = self.env["decimal.precision"].precision_get("Product Unit of Measure")
        for order in self:
            status = "no"
            if order.state in ("purchase", "done"):
                if order.force_received:
                    status = "received"
                elif all(
                    [
                        float_compare(
                            line.qty_received, line.product_qty, precision_digits=prec
                        )
                        >= 0
                        for line in order.order_line
                    ]
                ):
                    status = "received"
                elif any(
                    [
                        float_compare(line.qty_received, 0, precision_digits=prec) > 0
                        for line in order.order_line
                    ]
                ):
                    status = "partial"
            order.reception_status = status

```

I am ok with that, but a migration script is needed in v17

2025-07-30 08:17 UTC, bizzappdev commented
The change related to `receipt_status` is applied in our PR: https://github.com/astirpe/purchase-workflow/pull/2

2025-07-30 09:40 UTC, astirpe commented
Thank you @bizzappdev

2025-09-02 13:35 UTC, AaronHForgeFlow commented
Finally, it seems it it going to be a module split: https://github.com/OCA/purchase-workflow/pull/2781

2025-09-08 08:18 UTC, JoanSForgeFlow commented
Hi @astirpe,  

Since the migration in 17.0 was not compatible with the new Odoo field, we applied a module split to make it compatible.  

Here is the detailed proposal: https://github.com/OCA/purchase-workflow/pull/2201#issuecomment-3160414941  

And here it’s already implemented for 17.0: https://github.com/OCA/purchase-workflow/pull/2781  

Would you be open to adapting your migration to follow this approach?  

Thanks a lot!

2025-10-06 09:00 UTC, closed without merging