[9.0] [MIG] purchase_order_type module
OCA/purchase-workflow pull request #310
Opened 2016-12-17 10:12 UTC by cubells

- Updated README
- Updated views
- Removed invoice_method
- Updated onchange_partner_id method

cc @Tecnativa

2016-12-17 19:53 UTC, pedrobaeza requested changes
For giving any functionality added, you can add the stock picking type (only incoming ones), and incoterm information to purchase order types, and pass this information when changing the order type.

2016-12-17 19:53 UTC, pedrobaeza commented on purchase_order_type/README.rst
Include in the configuration section that you can predefine a purchase order type in the partner.

Include in the usage section that the type will be autofilled when selecting a partner that has a type set in its data.

2016-12-17 19:53 UTC, pedrobaeza commented on purchase_order_type/models/purchase_order.py
> +    def onchange_partner_id(self):
If you don't want to call super as this is an isolate operation, you can do:
```
    @api.onchange('partner_id', 'company_id')
    def onchange_partner_id_purchase_order_type(self):
        if self.partner_id.purchase_type:
            self.order_type = self.partner_id.purchase_type.id
```
Although you don't do this change, change the `if` part to the new API possibilities (no need to check the existence of each field before accessing the subfields).

2016-12-17 19:53 UTC, pedrobaeza commented on purchase_order_type/models/purchase_order_type.py
> +from openerp import models, fields
Order alphabetically

2016-12-19 08:14 UTC, pedrobaeza commented
What about the last point?:
```
For giving any functionality added, you can add the stock picking type (only incoming ones), and incoterm information to purchase order types, and pass this information when changing the order type.
```

2016-12-21 11:27 UTC, pedrobaeza commented on purchase_order_type/models/purchase_order.py
> +            self.incoterm_id = self.order_type.incoterm_id.id
This should be both also conditional. If the value is set, then you overwrite whatever it has. If not, you leave the previous value.

2016-12-21 12:18 UTC, pedrobaeza approved these changes
You can add also instructions for the 2 new fields, but not blocking. 9.0 commits to be squashed on merge.

2016-12-21 17:07 UTC, jjscarafia approved these changes

2016-12-21 19:10 UTC, merged