10.0 purchase fop shipping
OCA/purchase-workflow pull request #328
Opened 2017-02-07 16:18 UTC by mourad-ehm

This module allows to define a Free-Of-Paiment (FOP) shipping on supplier.
FOP shipping is a min order amount to got shipping free from supplier.
User can force confirm order if he/she wishes.

2017-02-07 16:38 UTC, legalsylvain requested changes
Hi @mourad-ehm. 
thanks a lot for this module. I'll use it for sure. Some minor remarks inline.
Otherwise, I think it's a good implementation of the free-of-payment concept.

(code review / no test).

2017-02-07 16:38 UTC, legalsylvain commented on purchase_fop_shipping/views/purchase_view.xml
> +			<field name="name">purchase.order.delivery.paid.form.view.inherit</field>
name field is unnessary.

2017-02-07 16:38 UTC, legalsylvain commented on purchase_fop_shipping/views/purchase_view.xml
> +	<data>
replace by <odoo> and underindent all the code.

2017-02-07 16:38 UTC, legalsylvain commented on purchase_fop_shipping/models/purchase.py
> +        help='Force confirm order under Free-Of-Paiment shipping',)
What about to have a group for this field. Maybe only purchase manager should have the right to check this box ?

2017-02-07 16:38 UTC, legalsylvain commented on purchase_fop_shipping/__manifest__.py
> +    'auto_install': False,
you can remove obsolete or default keys. (complexity, auto_install).

2017-02-07 16:38 UTC, legalsylvain commented on purchase_fop_shipping/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
could you use the last template ?
https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst
and about == title, you have to have the same number of '=' as the number of char in the tilte.

2017-02-07 16:38 UTC, legalsylvain commented on purchase_fop_shipping/README.rst
> +You need an Odoo/OCB installation v 10.0.
i guess that such lines are not necessary. You can freely remove all the empty (usage) or default section (installation)

2017-02-07 16:38 UTC, legalsylvain commented on purchase_fop_shipping/i18n/purchase_fop_shipping.pot
> +msgstr ""
it seems that your translation file is not up to date;

2017-02-08 08:33 UTC, elicoidal requested changes
There is some illogical functional behavior in this module.

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/README.rst
> +Usage
remove here as well

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/README.rst
> +`here <https://github.com/OCA/purchase-workflow/issues/new?body=module:%20purchase_fop_shipping%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%
adapt to newest template

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/__manifest__.py
> +    'version': '10.0.0.1.0',
10.0.1.0.0

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/__manifest__.py
> +    'maintainer': 'Akretion',
I think you can remove this key

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/models/purchase.py
> +        help='Force confirm order under Free-Of-Paiment shipping',)
Actually I would create a specific group FOP shipping manager

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/models/purchase.py
> +    fop_shipping = fields.Float(
shouldnot it be readonly or only for specific group

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/models/purchase.py
> +                    _('You cannot confirm a purchase order with amount under '
That looks contradictory for me: in README "FOP shipping is a min order amount to got shipping free from supplier."
We should be able to approve with a fee, no?

2017-02-08 08:33 UTC, elicoidal commented on purchase_fop_shipping/views/purchase_view.xml
> +	<data>
replace openerp by odoo

2017-02-08 09:06 UTC, AaronHForgeFlow commented on purchase_fop_shipping/models/purchase.py
> +        help='Force confirm order under Free-Of-Paiment shipping',)
Same remark

2017-02-08 09:06 UTC, AaronHForgeFlow commented on purchase_fop_shipping/models/purchase.py
> +        help='Free-Of-Paiment shipping reached',
Please correct the typo mistake

2017-02-08 09:14 UTC, lreficent commented on purchase_fop_shipping/models/purchase.py
> +        help='Free-Of-Paiment shipping reached',
"Payment" instead of "Paiment".

2017-02-08 10:01 UTC, mourad-ehm commented on purchase_fop_shipping/models/purchase.py
> +        help='Force confirm order under Free-Of-Paiment shipping',)
I'm ok for this proposition

2017-02-08 10:01 UTC, mourad-ehm commented on purchase_fop_shipping/__manifest__.py
> +    'auto_install': False,
Ok

2017-02-08 10:02 UTC, mourad-ehm commented on purchase_fop_shipping/README.rst
> +You need an Odoo/OCB installation v 10.0.
OK

2017-02-08 10:05 UTC, mourad-ehm commented on purchase_fop_shipping/README.rst
> +`here <https://github.com/OCA/purchase-workflow/issues/new?body=module:%20purchase_fop_shipping%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%
Ok

2017-02-08 10:06 UTC, mourad-ehm commented on purchase_fop_shipping/__manifest__.py
> +    'maintainer': 'Akretion',
You mean 'maintainer' key ?

2017-02-08 10:13 UTC, mourad-ehm commented on purchase_fop_shipping/models/purchase.py
> +    fop_shipping = fields.Float(
I think readonly is more safe. In some use case supplier can accept to apply exceptionaly a low a FOP for 1 order. Some user can think that the change is only for the current purchase, but it s not true.

2017-02-08 10:16 UTC, mourad-ehm commented on purchase_fop_shipping/models/purchase.py
> +                    _('You cannot confirm a purchase order with amount under '
Yes, if we force validation ( po.force_order_under_fop = true) we approve with a fee.

2017-02-08 14:35 UTC, legalsylvain approved these changes

2017-02-08 14:35 UTC, legalsylvain commented
:+1: Thanks !

2017-02-10 22:01 UTC, bealdav requested changes

2017-02-10 22:01 UTC, bealdav commented on purchase_fop_shipping/README.rst
> +Pruchase Free-Of-Paiment shipping
s/Pruchase/Purchase

2017-02-10 22:01 UTC, bealdav commented on purchase_fop_shipping/models/partner.py
> +        'FOP shipping', help='Min order amount for FOP shipping',)
order is ambiguous. Here I think it's purchase
s/order/purchase

2017-02-10 22:05 UTC, bealdav commented on purchase_fop_shipping/models/purchase.py
> +                    _('You cannot confirm a purchase order with amount under '
Mourad added "User can force confirm order if he/she wishes." in readme. So it's OK, no ?

2017-02-12 06:48 UTC, elicoidal commented on purchase_fop_shipping/models/purchase.py
> +                    _('You cannot confirm a purchase order with amount under '
clearer! :+1:

2017-02-12 06:49 UTC, elicoidal approved these changes

2017-02-13 08:16 UTC, mourad-ehm commented on purchase_fop_shipping/README.rst
> +Pruchase Free-Of-Paiment shipping
Thanks @bealdav. I fixed typo.

2017-02-13 09:17 UTC, bealdav commented
:+1:

2017-02-13 09:57 UTC, merged