[10.0] [MIG] Purchase Request Procurement (purchase_request_procurement)
OCA/purchase-workflow pull request #358
Opened 2017-03-10 09:00 UTC by ThomasBinsfeld

Migration of module purchase_request_procurement to 10.0
Depends on #424

2017-03-15 15:38 UTC, LoisRForgeFlow reviewed
Tested on runbot and it is fine, just some comments in lines.

2017-03-15 15:38 UTC, lreficent commented on purchase_request_procurement/models/procurement_order.py
> +    def _prepare_purchase_request_line(self, purchase_request, procurement):
why not to remove procurement from all the inputs and use self instead?

2017-03-15 15:38 UTC, lreficent commented on purchase_request_procurement/models/procurement_order.py
> +    def _prepare_purchase_request(self, procurement):
comment above

2017-03-15 15:38 UTC, lreficent commented on purchase_request_procurement/models/procurement_order.py
> +    def _search_existing_purchase_request(self, procurement):
same

2017-03-15 15:38 UTC, lreficent commented on purchase_request_procurement/test/purchase_request_from_procurement.yml
> +        assert line.product_id.id == procurement.product_id.id, "Product does not correspond."
I think there is not goal in mantaining the yml tests in v10. This is a good moment to get rid of this IMO.

2017-03-16 13:19 UTC, ThomasBinsfeld commented
@lreficent Thanks for the review. Done !

2017-03-16 13:53 UTC, LoisRForgeFlow approved these changes
Code review of new changes. LGTM now :+1:

2017-06-14 15:20 UTC, MiquelRForgeFlow approved these changes
LGTM :+1:

2017-06-15 08:10 UTC, aheficent commented
Code LGTM. Pending functional tests.

2017-06-16 08:04 UTC, lreficent commented
@ThomasBinsfeld Could you check the changes proposed to v9? (see: https://github.com/OCA/purchase-workflow/pull/398 and https://github.com/OCA/purchase-workflow/pull/412)

2017-06-29 13:08 UTC, benwillig commented
This PR now depends on #424.

2017-06-29 13:10 UTC, ThomasBinsfeld commented
Ping @lreficent

2017-06-29 15:33 UTC, lreficent commented
LGTM :+1: 

Just a minor comment, the commit is kind of a cherry-pick of the changes I proposed in v9, is it possible to keep the authority of the commit?

Thanks for the work!

2017-06-30 05:55 UTC, benwillig commented
Ups, I forgot to continue my cherry pick :laughing:. It's fixed now.

2017-06-30 09:21 UTC, lreficent commented
Thanks! :smile: 

Once the issues with travis are fixed I think this will be ready.

2017-07-06 09:34 UTC, AaronHForgeFlow requested changes
It fails when a procurement is cancelled :
![image](https://user-images.githubusercontent.com/19620251/27905040-006175a8-623f-11e7-8a38-2e584be201e2.png)

2017-07-06 09:36 UTC, benwillig commented
@aheficent At the moment, PR #424 has not been merged yet. That's why it doesn't work.

2017-07-06 10:48 UTC, aheficent commented
@benwillig I saw. Let's get that one merged first then. Thank you for telling me.

2017-08-28 14:06 UTC, lreficent commented
@ThomasBinsfeld Would you fix conflicts and add this v9 fix made here: https://github.com/OCA/purchase-workflow/commit/08c510912c89489be2c2235e1e96cc6d5826b17e

2017-08-28 14:44 UTC, ThomasBinsfeld commented
Rebased on 10.0

2017-08-28 14:46 UTC, lreficent commented
Great, thanks! Just the same that in previous cherry-pick: try to keep the authorship.

2017-08-28 14:58 UTC, ThomasBinsfeld commented
@lreficent Authorship restored ! :white_check_mark:

2017-09-10 11:03 UTC, D4N commented
#424 has been merged, so could this PR be merged, too? @aheficent Had some comments, but I guess they have been fixed, as #424 is merged.
If there are still issues, I offer my help, as I would really like this module in v10.

2017-09-21 09:07 UTC, AaronHForgeFlow approved these changes
Tested on runbot :+1:

2017-09-21 09:31 UTC, merged

2017-09-21 09:32 UTC, jbeficent commented
Thanks to all for your efforts!!