[10.0][MIG] product_by_supplier
OCA/purchase-workflow pull request #361
Opened 2017-03-14 14:54 UTC by lreficent

The changes included in this migration are:
* Basic migration actions (odoo tags, bump version, templates...).
* Update the README.
* Fix moved external IDs.

2017-03-14 15:29 UTC, lreficent commented
cc  @eficent

2017-03-14 16:41 UTC, gmeficent approved these changes
Functional review :+1:

2017-04-04 09:46 UTC, AaronHForgeFlow approved these changes
It works as expected :+1:

2017-04-04 09:50 UTC, pedrobaeza requested changes
Little redaction bugs.

2017-04-04 09:50 UTC, pedrobaeza commented on product_by_supplier/README.rst
> +This module add a new menu item 'Product by suppliers' in Purchases ->
s/add/adds

2017-04-04 09:50 UTC, pedrobaeza commented on product_by_supplier/README.rst
> +Products. It allows for users to be able to view a compiled list of products
Remove `for`

2017-04-04 09:50 UTC, pedrobaeza commented on product_by_supplier/README.rst
> +supplied by the supplier. This information is the corresponding to the
s/the supplier/their supplier

2017-04-04 11:06 UTC, lreficent commented on product_by_supplier/README.rst
> +supplied by the supplier. This information is the corresponding to the
I've attended these mistakes.

2017-04-04 15:20 UTC, pedrobaeza approved these changes

2017-04-04 15:21 UTC, merged