[IMP] purchase_discount: load price with discount in stock_move when …
OCA/purchase-workflow pull request #373
Opened 2017-04-03 15:57 UTC by cubells

…confirm a purchase order

2017-04-03 16:00 UTC, pedrobaeza commented on purchase_discount/models/purchase_order.py
> +    def _prepare_inv_line(self, account_id, order_line):
This method is not needed on v9

2017-04-03 16:00 UTC, pedrobaeza commented on purchase_discount/__openerp__.py
>      "version": "9.0.1.0.1",
Change version number

2017-04-03 16:01 UTC, pedrobaeza commented on purchase_discount/__openerp__.py
> +              "AvanzOSC, S.L., "
This little patch shouldn't be included in authors.

2017-04-28 14:45 UTC, sergio-teruel requested changes

2017-04-28 14:45 UTC, sergio-teruel commented on purchase_discount/models/purchase_order.py
> +        return price
Is multi?? Maybe you're missing a loop...

2017-04-28 14:46 UTC, pedrobaeza commented on purchase_discount/models/purchase_order.py
> +        return price
No, it isn't. super method has self.ensure_one()

2017-04-28 15:00 UTC, sergio-teruel commented on purchase_discount/models/purchase_order.py
> +        return price
Oks..

2017-04-28 15:01 UTC, sergio-teruel approved these changes

2017-04-28 16:37 UTC, carlosdauden approved these changes

2017-04-28 16:40 UTC, merged