[ADD] [9.0] purchase_request_to_rfq_order_approved
OCA/purchase-workflow pull request #388
Opened 2017-05-03 08:17 UTC by gmeficent

Related OCA/purchase-workflow/pull/381
This module computes the new PO state 'Approved' related to a Purchase Request Line to display it in the Purchase Request Line tree view and adds a 'Purchase Approved' filter.
@eficent

2017-05-03 08:47 UTC, JordiBForgeFlow requested changes

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/README.rst
> +Eficent. http://www.eficent.com/
Put your own name. Gisela Mora <gisela.mora@eficent.com>

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/__openerp__.py
> +        "purchase",
Redundand. Remove this one.

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/__openerp__.py
> +        "purchase_request",
Redundand

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/README.rst
> +   :target: http://odoo-community.org
https. See https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst. Use the maintainer section, as it is provided in that link.

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/__openerp__.py
> +              "Acsone SA/NV,"
Acsone has not contributed.

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/__openerp__.py
> +    "website": "http://www.eficent.com/",
replace with https://github.com/OCA/purchase-workflow

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/__openerp__.py
> +    "license": 'AGPL-3',
LGPL-3

2017-05-03 08:47 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/models/purchase_request.py
> +        rec.purchase_state = temp_purchase_state
This should go inside the for, when the if condition is applied.

2017-05-03 14:53 UTC, LoisRForgeFlow requested changes

2017-05-03 14:53 UTC, lreficent commented on purchase_request_to_rfq_order_approved/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/repo/github-com-oca-purchase-workflow-142
the correct link is: https://runbot.odoo-community.org/runbot/142/9.0, just follow OCA template module

2017-05-03 14:53 UTC, lreficent commented on purchase_request_to_rfq_order_approved/README.rst
> +Gisela Mora gisela.mora@eficent.com
`Gisela Mora <gisela.mora@eficent.com>` Do not forget *Thug lifes*  :joy:

2017-05-03 14:53 UTC, lreficent commented on purchase_request_to_rfq_order_approved/README.rst
> +Eficent. http://www.eficent.com/
Remove, just people here not companies.

2017-05-03 14:53 UTC, lreficent commented on purchase_request_to_rfq_order_approved/views/purchase_request_view.xml
> +                    help="At least a PO has been approved"/>
Make this only available when the feature is enabled in the company settings.

2017-05-05 17:14 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/models/purchase_request.py
> +            rec.purchase_state = temp_purchase_state
Please indent. The assigment of a value should only happen when the if any... condition is met.

2017-05-05 17:14 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/models/purchase_request.py
> +            temp_purchase_state = False
@gmeficent This statement results in many purchase request lines with state = False! Remove this.

2017-05-05 17:16 UTC, jbeficent commented on purchase_request_to_rfq_order_approved/views/purchase_request_view.xml
> +                    help="At least a PO has been approved"/>
Please move the filter upwards also.
![image](https://cloud.githubusercontent.com/assets/7683926/25756529/554307ec-31c7-11e7-90bf-aeefbe206cbe.png)

2017-05-05 17:17 UTC, jbeficent commented
@gmeficent Please add test cases.

2017-05-09 08:44 UTC, mreficent commented on purchase_order_approved/README.rst
> +   *Configuration* tab you can set the *Use State 'Approved' in Purchase
It should be nicer if you divide this paragraph into several #. lines.

2017-05-09 08:44 UTC, mreficent commented on purchase_order_approved/models/purchase_order.py
> +    # TODO: inhterit state but adding approved state in a position after 'to
inhterit → inherit

2017-05-09 08:44 UTC, mreficent commented on purchase_order_approved/views/purchase_order_view.xml
> +     License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl). -->
Usually the <code>.xml</code> files don't have copyrights comments.

2017-05-09 08:44 UTC, mreficent commented on purchase_order_approved/views/purchase_order_view.xml
> +        <field name="name">purchase.order.form - purchase_order_approved</field>
Usually people use uppercase letters for names.

2017-05-09 08:44 UTC, mreficent commented on purchase_request_to_rfq_order_approved/views/purchase_request_view.xml
> +                        help="At least a PO has been approved"/>
<code>help</code> attribute can be a long string. So it's nicer to read Purchase Order instead of PO.

2017-05-09 10:04 UTC, lreficent commented on purchase_order_approved/views/purchase_order_view.xml
> +     License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl). -->
OCA templete does https://github.com/OCA/maintainer-tools/blob/master/template/module/views/model_name_view.xml

2017-05-12 07:39 UTC, lreficent commented on purchase_order_approved/README.rst
> +Purchase Order Approved
You pushed this module by mistake

2017-06-09 15:49 UTC, mreficent commented
Please, rebase the PR squashing the minor commits 😙

2017-06-12 09:17 UTC, lreficent commented
Rebased and fixed conflicts, waiting tests.

2017-06-12 09:51 UTC, MiquelRForgeFlow approved these changes
LGTM :+1:

2017-06-12 11:46 UTC, merged

2017-06-12 12:39 UTC, lreficent commented
There was some issues in the README. Just write here to remember in future migrations.