[MIG] purchase_last_price_info: Migration to 10.0
OCA/purchase-workflow pull request #406
Opened 2017-06-05 14:58 UTC by kittiu

2017-06-26 16:11 UTC, kittiu commented
Can this one be merged?
(I see the runbot failed but with no reason).

2018-09-17 14:06 UTC, Abranes requested changes

2018-09-17 14:06 UTC, Abranes commented on purchase_last_price_info/models/product.py
>          self.last_supplier_id = lines[:1].order_id.partner_id
The `search` and `sorted` could be replaced by:
`self.env['purchase.order.line'].search(
            [('product_id', '=', self.id),
             ('state', 'in', ['purchase', 'done'])],
            order='date_order DESC', limit=1)`

Then you can change `lines[:1]` to `lines`.

Also you can take the `date_order` and `partner_id` from lines directly.

2018-09-17 14:06 UTC, Abranes commented on purchase_last_price_info/models/product.py
> +    )
Add the `digits=dp.get_precision('Product Price')` for display the same decimal precisions as in the lines.

2018-09-17 14:10 UTC, Abranes commented
Change `@api.one` for `@api.multi`.

For the rest, the module is working.

@kittiu if you can't do the changes I can do it.

2018-11-24 06:25 UTC, JayVora-SerpentCS commented
ping @kittiu

2018-11-24 06:32 UTC, nikul-serpentcs requested changes
Improve Code

2018-11-24 06:32 UTC, nikul-serpentcs commented on purchase_last_price_info/__manifest__.py
>      "website": "http://www.odoomrp.com",
Replace website URL as per [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L11)

2018-11-24 06:32 UTC, nikul-serpentcs commented on purchase_last_price_info/models/product.py
>  from openerp import api, fields, models
odoo

2018-11-24 13:39 UTC, pedrobaeza commented
Superseeded by #587

2018-11-24 13:39 UTC, closed without merging