[9.0][IMP] purchase_request: add cancelled state to lines.
OCA/purchase-workflow pull request #412
Opened 2017-06-15 09:37 UTC by lreficent

related to https://github.com/OCA/purchase-workflow/issues/396.

A new state is added to lines to enhance the behavior and flow of purchase_request and its submodules.

2017-06-15 09:39 UTC, lreficent commented
cc @benwillig @aheficent @jbeficent @sbidoul @gva-acsone

2017-06-15 11:02 UTC, AaronHForgeFlow approved these changes
:+1: I had to uninstall purchase_request_procurement to cancel the procurement and test properly

2017-06-21 07:19 UTC, benwillig requested changes

2017-06-21 07:19 UTC, benwillig commented on purchase_request/views/purchase_request_view.xml
> +                    <field name="cancelled"/>
@lreficent Can we make the field "cancelled" invisible in all tree view? The line is already grey when it has been cancelled so I guess we can hide it.

2017-06-21 10:43 UTC, lreficent commented on purchase_request/views/purchase_request_view.xml
> +                    <field name="cancelled"/>
I'm not sure that the user would realize about why the line is gray, that's why I prefer to show the field but yes, maybe you are right and I have to trust more the user :sweat_smile:

2017-06-21 14:22 UTC, benwillig approved these changes

2017-06-21 16:09 UTC, MiquelRForgeFlow approved these changes
LGTM :+1:

2017-06-21 16:10 UTC, JordiBForgeFlow approved these changes

2017-06-21 16:10 UTC, merged

2017-06-21 16:28 UTC, MiquelRForgeFlow reviewed
Please add migration scripts :octocat: