[MIG] purchase_order_revision module: migration to 10.0
OCA/purchase-workflow pull request #418
Opened 2017-06-22 06:44 UTC by cubells

- Update views
- Add README
- Rename files to new standard
- Update tests

cc @Tecnativa

2017-06-29 00:30 UTC, pedrobaeza requested changes

2017-06-29 00:30 UTC, pedrobaeza commented on purchase_order_revision/models/purchase_order.py
> +        old_revision = super(PurchaseOrder, self).copy(default=defaults)
You are not using 'orm.Model.copy' as the above comment says. Is not needed anymore? If so, just remove the comment.

2017-06-30 06:59 UTC, cubells commented on purchase_order_revision/models/purchase_order.py
> +        old_revision = super(PurchaseOrder, self).copy(default=defaults)
Done.

2017-06-30 07:40 UTC, pedrobaeza approved these changes

2017-10-03 10:28 UTC, rami-wafaie approved these changes
Review + Testing: Looks good to me 
:+1:

2017-10-10 15:08 UTC, antoniocanovas approved these changes
Functional revision.
LGTM

2017-10-10 15:10 UTC, pedrobaeza commented
@cubells please squash commits per author and I'll merge.

2017-10-11 09:40 UTC, cubells commented
@pedrobaeza done!

2017-10-11 10:03 UTC, merged

2017-10-18 15:57 UTC, mreficent commented
The runbot was red when this PR was merged :confused: