[9.0][ADD] purchase_open_qty
OCA/purchase-workflow pull request #421
Opened 2017-06-26 09:14 UTC by mreficent

Purchase Open Qty
=================

This module allows purchase users to identify what are the purchase orders that currently have quantities pending to invoice or to receive.

This module responds to https://github.com/OCA/purchase-workflow/issues/417 issue.

Also minor edits in other two modules.

cc: @jbeficent

2017-06-26 09:55 UTC, aheficent commented
Hi @mreficent I think that ` purchase_date_planned_manual` was not on purpose. Can you check?

2017-06-26 16:11 UTC, LoisRForgeFlow requested changes
Also add a view with filters for this new fields: This way a user can easily search for job pending to do.

2017-06-26 16:11 UTC, LoisRForgeFlow commented on purchase_open_qty/README.rst
> +
Please add a little usage description.

2017-06-26 16:11 UTC, LoisRForgeFlow commented on purchase_open_qty/models/purchase_order.py
> +                po.qty_to_invoice += po_line.qty_to_invoice
`po.qty_to_invoice = sum(po.mapped('order_line.qty_to_invoice'))` :wink:

2017-06-26 16:11 UTC, LoisRForgeFlow commented on purchase_open_qty/models/purchase_order.py
> +                po.qty_to_receive += po_line.qty_to_receive
same approach as above

2017-06-26 16:11 UTC, lreficent commented on purchase_open_qty/models/purchase_order.py
> +                                  default=False)
remove this default

2017-06-26 16:11 UTC, lreficent commented on purchase_open_qty/models/purchase_order.py
> +                                  default=False)
remove this default

2017-06-26 16:11 UTC, lreficent commented on purchase_open_qty/models/purchase_order.py
> +                                  string="Has qty pending to invoice",
Since this is not a boolean anymore, 'Qty to invoice' is going to be a better name.

2017-06-26 16:11 UTC, lreficent commented on purchase_open_qty/models/purchase_order.py
> +                                  string="Has qty pending to receive",
'Qty to receive'

2017-06-26 16:11 UTC, lreficent commented on purchase_open_qty/tests/test_purchase_open_qty.py
> +        # PURCHASE ORDER NUM 1
Why are you screaming?  :fearful: I don't like sentences in high caps, but it's up to you.

2017-06-26 16:11 UTC, lreficent commented on purchase_open_qty/tests/test_purchase_open_qty.py
> +            ('name', '=', 'Unit(s)')])[0].id
To do this I would tend to prefer to use directly the reference where this uom is created.

2017-06-26 16:11 UTC, lreficent commented on purchase_open_qty/tests/test_purchase_open_qty.py
> +            'price_unit': 1,
I will be converted to float but for more consistency use directly a float: `1.0`

2017-06-27 10:50 UTC, mreficent commented on purchase_open_qty/README.rst
> +
Added a bit usage description 😏

2017-06-27 11:00 UTC, JordiBForgeFlow approved these changes

2017-06-27 11:59 UTC, andhit-r commented
@mreficent why you did not add newly added view into tree or form view?

2017-07-03 07:40 UTC, LoisRForgeFlow approved these changes
Code review LGTM now :+1:

2017-07-03 08:22 UTC, AaronHForgeFlow requested changes
I received the items for a PO but the system shows that there's still qty pending to receive. Is that the expected behavior?
![image](https://user-images.githubusercontent.com/19620251/27784147-643fcd30-5fd9-11e7-9d10-64e86e1ce86b.png)

![image](https://user-images.githubusercontent.com/19620251/27784151-69bd3df6-5fd9-11e7-9af3-41a1ea027cc3.png)

2017-07-03 10:46 UTC, mreficent commented
@aheficent Thanks. Solved.

2017-07-03 11:28 UTC, AaronHForgeFlow approved these changes
:+1:  LGTM

Thanks for the quick fix @mreficent

2017-07-05 21:26 UTC, JordiBForgeFlow approved these changes

2017-07-05 21:27 UTC, jbeficent commented
@andhit-r Your comments have been attended to, and we have the sufficient approvals to merge.

2017-07-05 21:27 UTC, merged