[11.0] [MIG] purchase_request: Migration to 11.0 merge with purchase_request_procurement and purchase_request_to_rfq
OCA/purchase-workflow pull request #544
Opened 2018-04-26 15:03 UTC by hveficent

This module has been migrated from three different modules in order to keep functionality together. Since procurement has change in v11 seems to make sense.
Modules migrated:
- purchase_request
- purchase_request_procurement
- purchase_request_to_rfq

2018-04-27 16:05 UTC, hveficent commented
@jbeficent MTO routes are getting lost. Any idea/advice?

2018-04-30 15:12 UTC, JordiBForgeFlow approved these changes

2018-07-11 19:07 UTC, joezsweet commented
any eta to merge this one? thx

2018-08-07 07:56 UTC, HaraldPanten approved these changes
Functionally is working fine. Isn't it ready to approve?  THX! :+1:

2018-09-14 11:13 UTC, LoisRForgeFlow approved these changes
Some remarks on views, apart from that functionally looks good!

2018-09-14 11:13 UTC, lreficent commented on purchase_request/views/purchase_request_view.xml
> +                        <field name="origin" class="oe_inline"
I would move origin to a different place, it seem a little bit weird here for me.

2018-09-14 11:13 UTC, lreficent commented on purchase_request/views/purchase_request_view.xml
> +                                   attrs="{'readonly': [('is_editable','=', False)]}"/>
I reckon that `origin` field would fit fine before or after description.

2018-09-14 11:13 UTC, lreficent commented on purchase_request/views/purchase_request_view.xml
> +                            <field name="request_state"/>
Again, this seems a weird place to have more fields apart from name, state would fit better in a status bar as in almost any other document/model.

2018-10-24 04:43 UTC, nikul-serpentcs reviewed
Improve Code

2018-10-24 04:43 UTC, nikul-serpentcs commented on purchase_request/__manifest__.py
> +    "data": [
@hveficent IMO `data` sequence like [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L29)

2018-10-24 04:43 UTC, nikul-serpentcs commented on purchase_request/models/purchase_request.py
> +    name = fields.Char('Request Reference', size=32, required=True,
IMO remove `size` attribute everywhere, It's not needed.

2018-10-24 04:43 UTC, nikul-serpentcs commented on purchase_request/models/purchase_request.py
> +            raise Warning(
IMO use `UserError

2018-10-24 04:43 UTC, nikul-serpentcs commented on purchase_request/views/purchase_order_view.xml
> +    <data>
Remove `<data>`

2018-10-24 04:43 UTC, nikul-serpentcs commented on purchase_request/wizard/purchase_request_line_make_purchase_order.py
> +                raise exceptions.Warning(
use `UserError`

2018-10-24 04:43 UTC, nikul-serpentcs commented on purchase_request/wizard/purchase_request_line_make_purchase_order.py
> +                raise exceptions.Warning(
same here

2018-10-24 04:43 UTC, nikul-serpentcs commented on purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
> +    <data>
remove `<data>`

2018-10-26 08:49 UTC, etobella commented
Just a question, the functionality is similar to stock_request_purchase, or it has some differences?

2018-10-26 09:20 UTC, hveficent commented
They are alike, while in stock_request_purchase is an aiming solution to manage stockable products in a way much easier, in purchase_request you can request any kind of product, even services. So, it's a module that can be used inter-departmentally to demand  for requirements, for example, new coffe machine, but also for stock requirements.

2018-11-09 13:53 UTC, mreficent commented
@hveficent could you squash a bit?

2018-11-09 14:07 UTC, hveficent commented
Sure

2018-11-09 14:48 UTC, MiquelRForgeFlow approved these changes
LGTM

2018-12-05 09:43 UTC, bjeficent requested changes
When creating RFQ only vendors that are companies should be selectable.

![supplier](https://user-images.githubusercontent.com/44863841/49504627-5a54b700-f87a-11e8-9206-5c356d586893.png)

The purchase orders should be filtered by the selected vendor.

![po](https://user-images.githubusercontent.com/44863841/49504629-5b85e400-f87a-11e8-9824-d31571ccb45d.png)

2018-12-05 10:22 UTC, hveficent commented
Comments attended @bjeficent. Thanks for reviewing.

2018-12-05 10:27 UTC, MiquelRForgeFlow commented on purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
> +                        domain="[('partner_id', '=', supplier_id)]"/>
if supplier_id is False, then what happens?

2018-12-05 10:37 UTC, hveficent commented on purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
> +                        domain="[('partner_id', '=', supplier_id)]"/>
you can't create a PO.

2018-12-05 11:03 UTC, AaronHForgeFlow approved these changes
:+1: Functional review

2018-12-05 11:03 UTC, mreficent commented on purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
> +                        domain="[('partner_id', '=', supplier_id)]"/>
then maybe the field `supplier_id` should be required=True

2018-12-05 11:15 UTC, bjeficent approved these changes
Tested in local :+1:

2018-12-05 11:36 UTC, nikul-serpentcs requested changes
Improve Code

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/wizard/purchase_request_line_make_purchase_order.py
> +                                      default=False)
@hveficent `Boolean` always default False, so no need to `default=False`

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/wizard/purchase_request_line_make_purchase_order.py
> +        # if item.line_id.procurement_id:
remove Dead Code

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/wizard/purchase_request_line_make_purchase_order.py
> +from odoo.exceptions import UserError, Warning
Remove `Warning`  Use only `UserError` everywhere

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/models/product_template.py
> +        default=False,
`Boolean` always  default False, So no need to `default=False`.

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/models/purchase_order.py
> +                        raise exceptions.Warning(
@hveficent use `UserError`

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/security/purchase_request.xml
> +<data noupdate="0">
if `noupdate="0"` then remove `data`

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/security/purchase_request.xml
> +<data noupdate="0">
same here

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/views/purchase_request_view.xml
> +            <form string="Purchase Request" version="7.0">
remove `version`

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/views/purchase_request_view.xml
> +                                            <!--<field name="procurement_id"/>-->
remove Dead Code

2018-12-05 11:36 UTC, nikul-serpentcs commented on purchase_request/wizard/purchase_request_line_make_purchase_order.py
> +                                        required=False,
no need to `required=False`

2018-12-05 11:47 UTC, hveficent commented
Thanks @nikul-serpentcs for re-reviewing! Comments attended ;)

2018-12-05 11:55 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2018-12-13 14:57 UTC, merged