11.0 mig purchase commercial partner
OCA/purchase-workflow pull request #553
Opened 2018-06-05 07:25 UTC by andreasdsp

2018-09-19 18:17 UTC, nikul-serpentcs reviewed
Small Changes

2018-09-19 18:17 UTC, nikul-serpentcs commented on purchase_commercial_partner/__manifest__.py
> +    'website': 'http://www.akretion.com',
@andreasdsp Change URL as per [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L10)

2018-11-02 11:13 UTC, rousseldenis commented on purchase_commercial_partner/models/purchase.py
> +    commercial_partner_id = fields.Many2one(
@andreasdsp Set readonly=True.

2018-11-24 07:28 UTC, anandkansagra requested changes

2018-11-24 07:28 UTC, anandkansagra commented on purchase_commercial_partner/__manifest__.py
> +# -*- coding: utf-8 -*-
Please remove `# -*- coding: utf-8 -*-`

2022-07-10 12:25 UTC, closed without merging