[11.0][ADD]purchase_product_usage
OCA/purchase-workflow pull request #626
Opened 2019-01-09 13:10 UTC by aheficent

### Description
When purchasing, companies may need to specify different accounts depending on the usage the company is going to give to the part. Usages can be very diverse as for example: internal use, marketing use, testing use.

With this module, we can define different usages in the company for products. Purchase Users can specify the use the company expect to use the product for, and use the specific account for that.

### Usage
In order to test it, first activate usages for purchased products on settings.

Then, in the PO line set the usage of the purchased product. If the product is a consumable or a service and the valuation is periodic then the invoice will take the account from the usage. In any other case the normal behavior is expected.

2019-01-10 08:52 UTC, HviorForgeFlow requested changes
Functional review @aheficent 
- Purchase users are unable to select Usage on Quotations.
- Once I selected Product Usages in Purchases on Purchase Settings I can't remove Usages on products for Purchases options in user settings.

2019-01-10 12:22 UTC, AaronHForgeFlow commented
Thanks for reporting @hveficent I think it is fixed now

2019-01-11 04:28 UTC, nikul-serpentcs requested changes
Improve Code

2019-01-11 04:28 UTC, nikul-serpentcs commented on purchase_product_usage/views/purchase_order_line_view.xml
> +</odoo>
@aheficent add new blank line

2019-01-11 04:28 UTC, nikul-serpentcs commented on purchase_product_usage/tests/test_purchase_product_usage.py
> +        cls.product_1 = cls.env['product.product'].create({
@aheficent `cls.env['product.product']` use multiple time so use as like global variable

2019-01-11 09:33 UTC, aheficent commented
@nikul-serpentcs Thanks for the tip. Done.

2019-01-15 09:12 UTC, LoisRForgeFlow reviewed
Some comments to align with the fact that you dropped the settings.

2019-01-15 09:12 UTC, lreficent commented on purchase_product_usage/views/purchase_order_line_view.xml
> +                <field name="usage_id" groups="purchase_product_usage.group_purchase_product_usage"/>
remove the group here, so anyone can specify a usage for a PO line.

2019-01-15 09:12 UTC, lreficent commented on purchase_product_usage/readme/CONFIGURE.rst
> +Activate usages for purchased products on settings
drop this line

2019-01-15 09:27 UTC, LoisRForgeFlow commented
I miss the usage in the form view for purchase lines: 
![image](https://user-images.githubusercontent.com/23449160/51170966-f5946f80-18af-11e9-9691-c224b36e3cd7.png)

2019-01-15 12:45 UTC, aheficent commented
Latest changes:

- Add a default product for usages. The product is added automatically to the PO line when selecting the usage.
- Fixes commented by @lreficent:
  - Add usage to PO line form view 
  - Remove groups from view so every purchase user can see and select

2019-01-15 12:57 UTC, aheficent commented
I forgot to add the domain in the products. Only consumables or services can be selected.

2019-01-15 14:00 UTC, lreficent commented on purchase_product_usage/models/purchase_order_line.py
> +        if self.usage_id.product_id:
`... and not self.product_id`

2019-01-15 14:38 UTC, aheficent commented on purchase_product_usage/models/purchase_order_line.py
> +        if self.usage_id.product_id:
:sweat_smile:

2019-01-15 16:47 UTC, LoisRForgeFlow approved these changes
Thanks! this looks good for me now :+1:

2019-01-15 16:48 UTC, lreficent commented
@aheficent could you squash?

@nikul-serpentcs please update your review

2019-01-16 12:26 UTC, AaronHForgeFlow commented
Hi @nikul-serpentcs  @hveficent Could you update your review please?

2019-01-16 13:04 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2019-01-24 12:54 UTC, JordiBForgeFlow approved these changes
:+1:  Technical and functional review. Tested on runbot.

2019-01-24 13:10 UTC, JordiBForgeFlow approved these changes
:+1: Code review and functional tests. Looks good!

2019-01-24 14:03 UTC, merged