12.0 mig purchase landed cost
OCA/purchase-workflow pull request #632
Opened 2019-01-17 23:52 UTC by rvalyi

standard v12 migration:

- product.uom -> uom.uom
- label with for
- now depends on new purchase_stock module to ensure stock.move has the required purchase_line_id field

2019-01-18 08:55 UTC, pedrobaeza commented
Please fix little runbot warning:
```
WARNING openerp_test odoo.models: The model import.landed.cost.pickings.wizard has no _description

```

2019-02-24 15:00 UTC, novawish requested changes
We are facing an issue with multi-currency configuration: The Vendor Bills may have different currencies compared with company's currency. I added a suggestion, can you tell me what you think?

2019-02-24 15:00 UTC, novawish commented on purchase_landed_cost/wizard/import_invoice_line.py
> +            'expense_amount': self.invoice_line.price_subtotal,
Can we do a conversion (`compute`) form foreign currency for invoices that have different currency from company's currency (in multi-currency)?

2019-02-24 15:00 UTC, novawish commented on purchase_landed_cost/models/purchase_cost_distribution.py
> +        self.expense_amount = self.invoice_line.price_subtotal
Can we do a conversion (`compute`) form foreign currency for invoices that have different currency from company's currency (in multi-currency)?

2019-02-24 15:56 UTC, novawish commented on purchase_landed_cost/wizard/import_invoice_line.py
> +            'expense_amount': self.invoice_line.price_subtotal,
After thinking again, i think we can use field `price_subtotal_signed` instead

2019-02-24 15:56 UTC, novawish commented on purchase_landed_cost/models/purchase_cost_distribution.py
> +        self.expense_amount = self.invoice_line.price_subtotal
After thinking again, i think we can use field `price_subtotal_signed` instead

2019-02-25 16:12 UTC, novawish commented on purchase_landed_cost/wizard/import_landed_cost_pickings_wizard.py
> +        domain="[('id', 'in', possible_picking_ids[0][2])]")
I tested and apparently this does not work anymore.
I think we don't need `possible_picking_ids` and we can write a function that return directly the domain like this:
![image](https://user-images.githubusercontent.com/31387997/53350865-9fa4f400-3952-11e9-9db3-a008023b3a10.png)

2019-08-19 14:41 UTC, pedrobaeza commented
Superseeded by #706

2019-08-19 14:41 UTC, closed without merging