[12.0][MIG] purchase_date_planned_manual
OCA/purchase-workflow pull request #730
Opened 2019-07-30 16:34 UTC by hveficent

Standard Migration

* purchase_stock dependency added (not sure if it is correct)

CC @Eficent

2019-07-31 11:04 UTC, MiquelRForgeFlow requested changes

2019-07-31 11:04 UTC, mreficent commented on purchase_date_planned_manual/tests/test_date_planned_manual.py
> +        self.rule = first(self.route_buy_id.pull_ids)
```suggestion
        self.rule = first(self.route_buy_id.rule_ids)
```

2019-07-31 15:30 UTC, MiquelRForgeFlow approved these changes

2019-08-23 05:43 UTC, AdriaGForgeFlow approved these changes
Functional test and code review :+1:

2019-08-23 07:24 UTC, rousseldenis approved these changes
Code review

2019-09-13 11:17 UTC, jbeficent commented
/ocabot merge

2019-09-13 12:50 UTC, merged