[12.0][REF] migrate and refactor purchase_analytic_global
OCA/purchase-workflow pull request #801
Opened 2019-11-26 10:20 UTC by i-vyshnevska

migrate https://github.com/OCA/purchase-workflow/pull/228

2019-11-27 15:53 UTC, sebalix approved these changes

2019-11-28 08:12 UTC, jcoux approved these changes

2019-11-28 08:12 UTC, jcoux commented on purchase_analytic_global/__manifest__.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2019-11-28 08:12 UTC, jcoux commented on purchase_analytic_global/models/purchase.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2019-11-28 08:12 UTC, jcoux commented on purchase_analytic_global/__manifest__.py
> +# © 2014-2016 Camptocamp SA
```suggestion
# Copyright 2014-2019 Camptocamp SA
```

2019-12-16 16:10 UTC, yvaucher approved these changes
LGTM

Small proposal to improve the help string.

2019-12-16 16:10 UTC, yvaucher commented on purchase_analytic_global/models/purchase.py
> +        "to use different accounts, set different account on lines",
```suggestion
        "to use different accounts, define the account at line level.",
```

2019-12-18 17:41 UTC, i-vyshnevska commented
@yvaucher updated, squashed

2019-12-19 08:21 UTC, dreispt commented
/ocabot merge

2020-01-14 08:47 UTC, HviorForgeFlow commented
/ocabot merge

2020-01-14 09:18 UTC, HviorForgeFlow requested changes

2020-01-14 09:18 UTC, HviorForgeFlow commented on purchase_analytic_global/models/purchase.py
> +        string="Analytic Account",
Odoo doesn't like same string in 2 fields, you must rename it, because Analytic Account it is already used on account_analytic_ids field.

2020-01-14 10:28 UTC, merged