[12.0][IMP]purchase_request
OCA/purchase-workflow pull request #819
Opened 2019-12-11 08:56 UTC by AaronHForgeFlow

`requested_by` should not be copied when duplicating a purchase request

cc @forgeflow

2019-12-11 10:06 UTC, AaronHForgeFlow commented
cc @HviorForgeFlow

2019-12-11 10:17 UTC, HviorForgeFlow approved these changes

2019-12-12 07:15 UTC, ps-tubtim approved these changes

2019-12-12 09:54 UTC, AaronHForgeFlow commented
I completed the fix by adding the user that duplicates the record as requestor. It makes sense IMO.

2019-12-12 10:36 UTC, HviorForgeFlow requested changes
Not required in V12

2019-12-12 10:36 UTC, HviorForgeFlow commented on purchase_request/models/purchase_request.py
> +            'requested_by': self.env.user.id,
Not required in V12.

2019-12-12 10:46 UTC, AaronHForgeFlow commented
@HviorForgeFlow Good to know. Removed that commit. Thanks.

2019-12-12 11:10 UTC, HviorForgeFlow approved these changes

2019-12-17 12:12 UTC, AaronHForgeFlow commented
Ready to merge

2019-12-17 12:19 UTC, HviorForgeFlow commented
/ocabot merge patch

2019-12-17 15:30 UTC, merged