[13.0][MIG][WIP] purchase force invoiced
OCA/purchase-workflow pull request #828
Opened 2019-12-18 02:25 UTC by kongrattapong

Work in procress.

2020-02-10 06:02 UTC, kittiu commented
Functional and technical tested,
LGTM :+1:

2020-02-10 06:02 UTC, kittiu approved these changes

2020-12-02 10:33 UTC, HviorForgeFlow requested changes
In addition, can you change Eficent -> Forgeflow? Thanks!

2020-12-02 10:33 UTC, HviorForgeFlow commented on purchase_force_invoiced/__manifest__.py
> +    "author": "Eficent," "Odoo Community Association (OCA)",
```suggestion
    "author": "Eficent, Odoo Community Association (OCA)",
```

2020-12-02 11:27 UTC, kittiu commented
> In addition, can you change Eficent -> Forgeflow? Thanks!

Replied. Thanks!

2021-02-16 11:44 UTC, HviorForgeFlow reviewed
Can you rebase this branch? Thanks!

2021-02-23 09:47 UTC, kittiu commented
Rebased

2021-02-25 08:43 UTC, HviorForgeFlow approved these changes

2021-02-25 08:52 UTC, HviorForgeFlow requested changes

2021-02-25 08:52 UTC, HviorForgeFlow commented on purchase_force_invoiced/view/purchase_view.xml
> -<?xml version="1.0" encoding="utf-8"?>
XML header is missing

2021-03-26 06:52 UTC, HviorForgeFlow approved these changes

2021-03-26 06:52 UTC, HviorForgeFlow commented
/ocabot merge nobump

2021-03-26 07:35 UTC, merged