[MIG] Migrated purchase commercial partner to v13.
OCA/purchase-workflow pull request #868
Opened 2020-02-26 11:43 UTC by sudhir-erpharbor

2020-03-18 07:54 UTC, newtratip requested changes
@sudhir-erpharbor Small change.

2020-03-18 07:54 UTC, newtratip commented on purchase_commercial_partner/views/purchase.xml
> +<?xml version="1.0" encoding="utf-8"?>
Please change file's name to purchase_views.xml
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#file-naming

2020-04-06 09:56 UTC, newtratip commented
@sudhir-erpharbor Could you squash your commit ?

2020-04-07 08:44 UTC, sudhir-erpharbor commented
> @sudhir-erpharbor Could you squash your commit ?

Done. Thanks for the review.

2020-07-01 11:45 UTC, newtratip approved these changes
LGTM :+1:

2020-10-08 11:05 UTC, CasVissers-360ERP approved these changes
LGTM, functional test.

2020-11-10 14:09 UTC, HviorForgeFlow commented
/ocabot merge nobump

2020-11-10 16:41 UTC, merged