[WIP]13.0 mig purchase order product recommendation brand
OCA/purchase-workflow pull request #883
Opened 2020-03-23 16:29 UTC by manuelcalerosolis

2020-04-15 14:49 UTC, chienandalu requested changes
Rebase and resolve conflicts

2021-03-05 10:12 UTC, CarlosRoca13 commented
Please @sergio-teruel @chienandalu review it again

2021-03-08 09:30 UTC, sergio-teruel approved these changes

2021-03-08 13:01 UTC, pedrobaeza commented
/ocabot merge nobump

2021-03-08 14:21 UTC, merged