[12.0][ADD] purchase_order_line_price_history: new module
OCA/purchase-workflow pull request #945
Opened 2020-07-17 03:35 UTC by ernestotejeda

similar to https://github.com/OCA/sale-workflow/tree/12.0/sale_order_line_price_history, but for purchases.

TT24733

2020-07-17 05:50 UTC, sergio-teruel requested changes

2020-07-17 05:50 UTC, sergio-teruel commented on purchase_order_line_price_history/README.rst
> +#. You can select other customer or leave it empty to see the price history for
Change to vendor or supplier

2020-07-17 05:50 UTC, sergio-teruel commented on purchase_order_line_price_history/README.rst
> +   all customers.
the same

2020-07-17 05:50 UTC, sergio-teruel commented on purchase_order_line_price_history/i18n/es.po
> +msgid "Customer"
Reference to supplier

2020-07-17 05:50 UTC, sergio-teruel commented on purchase_order_line_price_history/i18n/es.po
> +msgid "Price history per customer"
Reference to supplier

2020-07-17 05:50 UTC, sergio-teruel commented on purchase_order_line_price_history/wizards/purchase_order_line_price_history.py
> +        string='Customer',
Change by Supplier

2020-07-17 14:47 UTC, ernestotejeda commented
@sergio-teruel Changes done.

2020-07-20 06:20 UTC, sergio-teruel approved these changes

2020-07-20 07:13 UTC, pedrobaeza requested changes

2020-07-20 07:13 UTC, pedrobaeza commented on purchase_order_line_price_history/tests/test_purchase_order_line_price_history.py
> +        cls.partner_1 = cls.env.ref('base.res_partner_1')
Don't use demo data, but create new partners and products.

2020-07-20 20:07 UTC, pedrobaeza approved these changes

2020-07-20 20:07 UTC, pedrobaeza commented
/ocabot merge nobump

2020-07-20 21:28 UTC, merged