[13.0][ADD]Purchase_Work_Acceptance_Late_Fine
OCA/purchase-workflow pull request #956
Opened 2020-07-30 14:46 UTC by kranokporn

This module extends Purchase Work Acceptance  by adding the ability to calculate late delivery fines to vendor. To Fines the vendor, the company will issue the "Customer Invoice" for the fine amount calculated in WA.

Deployment:
1.Restart Odoo.
2.Install  Module Purchase Work Acceptance Late Fine. Depends Module Purchase Work Acceptance.

Config:
1.Purchase > Configuration > Settings
2.Check 'Enable Late Fine on Work Acceptance'

Work in process : Late WA in Customer Invoice.
Todo : Test script

cc. @kittiu Can you review please?

2020-07-31 03:28 UTC, kranokporn commented
Waiting for merge : https://github.com/OCA/purchase-workflow/pull/957
So can continue with the process.

2020-07-31 04:38 UTC, kittiu requested changes

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +    _description = "Journal Entries"
No need to overwrite or change the description again. We want to extend this model only.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +    )
Add some help, because this field is not easy to understand.
i.e.,
help="For the supplier with late penalty (during work acceptance), choosing the late WA to get the amount this partner need to pay.",

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +        return [("id", "in", wa.ids)]
```suggestion
    def _domain_late_wa(self):
        wa = self.env["work.acceptance"].search([("late_fine", ">", 0)])
        return [("id", "in", wa.ids)]
```
Use method name that starts with `_domain`. More on coding standard.

Also, I think the logic is not enough here. We should make sure that, if that WA is already used in any active document, it must not show.
For example, if WA is already used in invoice (state != cancel) it must not show. Otherwise, use will use this WA multiple times (we don't want that).

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +    def _onchange_wa_id(self):
Naming convention. this can make sure it is not same as what is used before, as the name is unique.
```suggestion
    def _onchange_late_wa_id(self):
```
Note: when write code, please make sure that, our new feature do not affect existing one. For example, we may have to serach the entire system that no method with the same name is used else where.

Don't forget that, Odoo is modular.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +        return [("id", "in", wa.ids)]
If partner is already selected, show only WA of selected partner.
If partner is not selected, show all valid WAs.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +                self._onchange_currency()
```suggestion
self._onchange_currency()
```
Should be outside? (why do we need this anyway).

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +        wa_lines = self.late_wa_id
Just 1 WA, no (s). Also, we shouldn't need to use for...loop, right? Because, we don't have multiple WA here.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +                new_line.name = "รายได้ค่าปรับส่งของล่าช้า WA เลขที่ %s" % (line.name)
```suggestion
                new_line = new_lines.new(line._prepare_account_move_line(self))
```
Everything should be in function _prepare_account_move_line(). This is the point of having sub function.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +                new_line._onchange_price_subtotal()
Do we need to call this function?
```suggestion
                new_line._onchange_price_subtotal()
```
Isn't this function called automatically already?

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_company.py
> +    wa_fine_rate = fields.Monetary(string="Rate",)
Rate is, so it should be float.
```suggestion
    wa_fine_rate = fields.Float(
        string="Rate",
    )
```

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_company.py
> +        comodel_name="account.account", string="Revenue Account",
```suggestion
        comodel_name="account.account",
        string="Revenue Account",
```

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_config_settings.py
> +        readonly=False,
```suggestion
```

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_config_settings.py
> +    wa_fine_rate = fields.Monetary(
Float

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/work_acceptance.py
> +    fine_rate = fields.Monetary(
Float

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/work_acceptance.py
> +    _description = "Work Acceptance"
```suggestion
```

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/work_acceptance.py
> +        string="Fine Amount", compute="_compute_late_fine", store=True,
May be this shouldn't be a compute field.
It should be calculated by onchange.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/work_acceptance.py
> +    def _compute_late_days(self):
Compute field is multi by nature.
Only if date_accept and date_due has value, we will continue calculate., i.e.,
```
for rec in self:
  if not rec.date_accept or not rec.date_due:
    continue
  rec.late_days = (rec.date_accept - rec.date_due).days
```

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/work_acceptance.py
> +    def _compute_late_days(self):
Note: your logic is quite confusing. I am not sure why you try to loop through date? Or the variable naming is not ok.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +                new_line.name = "รายได้ค่าปรับส่งของล่าช้า WA เลขที่ %s" % (line.name)
To use a fixed string, must use _("xxx") translation.
```
new_line.name = _("Work Acceptance Late Fine %s") % (line.name)
```

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/work_acceptance.py
> +    def _compute_late_fine(self):
This should be onchange per say.

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/readme/DESCRIPTION.rst
> +This module extends Purchase Work Acceptance  by adding the ability to calculate late delivery fines to vendor.
```suggestion
This module extends Purchase Work Acceptance by adding the ability to calculate late delivery fines to vendor.
```

2020-07-31 04:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/security/ir.model.access.csv
> +access_work_acceptance_manager,access_work_acceptance_manager,model_work_acceptance,purchase.group_purchase_manager,1,1,1,1
Do we need this again? I though we had it in module purchase_work_acceptance already.

2020-08-03 10:14 UTC, kranokporn commented
Todo : test script
Waiting for merge : https://github.com/OCA/purchase-workflow/pull/957
So can continue with the process.

2020-08-25 11:30 UTC, Saran440 commented
- Fixed error when not installed `purchase_work_acceptance_evalutaion` module
- Fixed field Float fine_rate to Monetary
- Generated readme file
- Compute `late_days`. if you not received product yet, late_dats will compute from today (Approximately).

2020-10-26 03:41 UTC, Saran440 commented
Ready for review.

2020-11-13 09:36 UTC, kittiu requested changes
@Saran440 I just know that we need to use the word "Fines" for this kind of penalty fee. (fines != fine). Please do the following,

* All label "Late Fine" need to change to "Late Delivery Fines", or "WA Late Delivery Fines" as appropriate.
* Module name, and all fields, need to change from "xxx_fine" to "xxx_fines"

2020-11-13 09:37 UTC, kittiu commented on purchase_work_acceptance_late_fine/__manifest__.py
> +    "name": "Purchase Work Acceptance Late Fine",
```suggestion
    "name": "Purchase Work Acceptance - Late Delivery Fines",
```

2020-11-13 09:37 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +        """ Auto fill values from WA late fine """
```suggestion
        """ Auto fill values from WA delivery late fines """
```

2020-11-13 09:37 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_company.py
> +        comodel_name="account.account", string="Late Fine Revenue Account",
```suggestion
        comodel_name="account.account", string="Late Delivery Fines Revenue Account",
```

2020-11-13 09:38 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_company.py
> +        comodel_name="account.account", string="Late Fine Revenue Account",
And all others...

2020-11-13 09:54 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_company.py
> +        comodel_name="account.account", string="Late Fine Revenue Account",
Currently, system will use "Accept Date" - "Due Date" to calculate late days
![image](https://user-images.githubusercontent.com/1973598/99058976-7e75b280-25d0-11eb-86aa-aba9dec3acc5.png)

Accept date = date when click the button. I think this is very strict. Also once accepted, user can't change the late days or rated / day.

I think we should make late days and rate / day as editable even Accepted. But make sure all changes are logged in Chatter as Track=True.

2020-11-13 09:59 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/res_company.py
> +        comodel_name="account.account", string="Late Fine Revenue Account",
![image](https://user-images.githubusercontent.com/1973598/99059551-55a1ed00-25d1-11eb-9d2a-0d9b3b035cf0.png)

1. Create and Edit should be disable here.
2. Select WA, should auto fill Partner. (if user select partner first, also filer only WA of partner).

2020-11-13 09:59 UTC, kittiu commented
Currently, system will use "Accept Date" - "Due Date" to calculate late days
![image](https://user-images.githubusercontent.com/1973598/99058976-7e75b280-25d0-11eb-86aa-aba9dec3acc5.png)

Accept date = date when click the button. I think this is very strict. Also once accepted, user can't change the late days or rated / day.

I think we should make late days and rate / day as editable (for purchase manager group) even Accepted. But make sure all changes are logged in Chatter as Track=True.

2020-11-13 10:00 UTC, kittiu commented
![image](https://user-images.githubusercontent.com/1973598/99059551-55a1ed00-25d1-11eb-9d2a-0d9b3b035cf0.png)

1. Create and Edit should be disable here.
2. Select WA, should auto fill Partner. (if user select partner first, also filer only WA of partner).

2020-11-13 10:06 UTC, kittiu commented
Currently, there is only option to direct create Customer Invoice + WA.
But from Work Acceptance window, if status = accept and fines > 0, I think we should have Action > Create Fines Invoice.

2020-11-13 10:12 UTC, kittiu commented
![image](https://user-images.githubusercontent.com/1973598/99060865-458b0d00-25d3-11eb-8084-fa7c6211033b.png)

Create Customer Invoice, and Post -> error required field, but I can't see the field anywhere.

2020-11-13 10:12 UTC, kittiu commented on purchase_work_acceptance_late_fine/__manifest__.py
> +    "maintainers": ["kranokporn"],
```suggestion
    "maintainers": ["Saran440"],
```

2020-11-13 10:13 UTC, kittiu commented on purchase_work_acceptance_late_fine/models/account_move.py
> +    def _onchange_late_wa_id(self):
This onchange should auto fill partner_id too.

2020-11-15 09:18 UTC, Saran440 commented
Fixed
- change module name to `purchase_work_acceptance_late_fines`, change word `fine `to `fines`
- add reverse compute fields late days
- fix late_wa_id is can't create wa from invoice
- fix onchange domain when select `late_wa_id`
- add button `create fines invoice` from wa form and action on tree view

To do
- [ ] Test script

2021-01-23 02:48 UTC, kittiu commented
Moved to https://github.com/OCA/purchase-workflow/pull/1020

2021-01-23 02:48 UTC, closed without merging