[13.0][ENH] purchase_tier_validation, adding Escalation option
OCA/purchase-workflow pull request #967
Opened 2020-08-29 07:28 UTC by kittiu

2020-09-28 10:43 UTC, HviorForgeFlow approved these changes

2020-10-01 09:41 UTC, ps-tubtim approved these changes

2020-11-03 08:33 UTC, HviorForgeFlow requested changes
Don't not merge, https://github.com/OCA/server-ux/pull/197 has been closed and replaced by https://github.com/OCA/server-ux/pull/220, module is intend to be splitted.

2020-11-03 10:59 UTC, kittiu commented
Sorry I should have closed this.

2020-11-03 10:59 UTC, closed without merging