[WIP][14.0][MIG] purchase_request
OCA/purchase-workflow pull request #995
Opened 2020-10-15 15:01 UTC by HviorForgeFlow

Standard migration to 14.0

Not sure how to fix this
```
odoo.exceptions.ValidationError: Error while validating view:

Field product_uom_category_id used in field product_uom default domain ([('category_id', '=', product_uom_category_id)]) must be present in view but is missing.

View name: purchase.order.line.form2
Error context:
 view: ir.ui.view(1418,)
 xmlid: purchase_order_line_form2_sub
 view.model: purchase.order.line
 file: /home/hvior/Projects/odoo/14.0/addons/OCA/purchase-workflow/purchase_request/views/purchase_request_line_view.xml
```

CC @ForgeFlow

2020-10-15 16:24 UTC, AaronHForgeFlow reviewed
Functional tests looks great so far. Including mixing purchase requests lines, cancellations, notifications to requested by users and applying the minimum order quantity! Cool.

2020-10-16 05:50 UTC, HviorForgeFlow commented
Weird behavior on invisible tag:
Using attrs:
![image](https://user-images.githubusercontent.com/32061121/96217811-b1059e80-0f83-11eb-811f-305b981bbdfc.png)
Result:
![image](https://user-images.githubusercontent.com/32061121/96217848-ca0e4f80-0f83-11eb-8fec-7acc23dbef10.png)

Using "legacy" invisible, I see is still used in some views:
![image](https://user-images.githubusercontent.com/32061121/96217918-eb6f3b80-0f83-11eb-9bb9-00d35f570adf.png)

Result:
![image](https://user-images.githubusercontent.com/32061121/96217969-02ae2900-0f84-11eb-91c6-336fd9c05a7f.png)

@dreispt

2020-10-16 07:10 UTC, JordiMForgeFlow commented
Functional tests review.
It may be useful to have a string naming the checkbox for the product configuration.
![image](https://user-images.githubusercontent.com/71635103/96223960-11e6a400-0f8f-11eb-9fb3-6da1a5388dbe.png)

2020-10-16 08:24 UTC, AaronHForgeFlow commented
> Weird behavior on invisible tag:
> Using attrs:
> ![image](https://user-images.githubusercontent.com/32061121/96217811-b1059e80-0f83-11eb-811f-305b981bbdfc.png)
> Result:
> ![image](https://user-images.githubusercontent.com/32061121/96217848-ca0e4f80-0f83-11eb-8fec-7acc23dbef10.png)
> 
> Using "legacy" invisible, I see is still used in some views:
> ![image](https://user-images.githubusercontent.com/32061121/96217918-eb6f3b80-0f83-11eb-9bb9-00d35f570adf.png)
> 
> Result:
> ![image](https://user-images.githubusercontent.com/32061121/96217969-02ae2900-0f84-11eb-91c6-336fd9c05a7f.png)
> 
> @dreispt

Perhaps attrs requires a domain, or a condition?

2020-10-16 09:35 UTC, HviorForgeFlow commented
I've tried using [(1, ,'=', 1)] domain and it's still showing :disappointed:

2020-10-16 10:27 UTC, HviorForgeFlow commented
> Functional tests review.
> It may be useful to have a string naming the checkbox for the product configuration.
> ![image](https://user-images.githubusercontent.com/71635103/96223960-11e6a400-0f8f-11eb-9fb3-6da1a5388dbe.png)

solved!

2020-10-16 10:29 UTC, AaronHForgeFlow commented
> I've tried using [(1, ,'=', 1)] domain and it's still showing

:confused:  better leave it as invisible="1" then

2020-10-16 13:38 UTC, JordiMForgeFlow approved these changes
Reviewed changes

2020-10-20 11:43 UTC, digitalsatori requested changes

2020-10-20 11:43 UTC, digitalsatori commented on purchase_request/models/purchase_request.py
> +        self.move_count = len(
self may not be a singleton, need a for loop here

2020-10-20 11:43 UTC, digitalsatori commented on purchase_request/models/purchase_request.py
> +        self.purchase_count = len(self.mapped("line_ids.purchase_lines.order_id"))
`self` may not be a singleton, need a for loop here.

2020-10-20 13:42 UTC, HviorForgeFlow commented
@digitalsatori comments attended, thanks for your review.

2020-10-20 13:45 UTC, AaronHForgeFlow approved these changes

2020-10-22 04:07 UTC, digitalsatori approved these changes
LGTM

2020-10-22 12:49 UTC, dreispt commented
/ocabot merge nobump

2020-10-22 12:54 UTC, HviorForgeFlow commented
It is not ready yet, let me add remaining forward port

2020-10-22 15:05 UTC, AaronHForgeFlow requested changes
#996 is still pending

2020-10-23 06:08 UTC, HviorForgeFlow commented
@AaronHForgeFlow company dependant feature added

2020-10-27 09:48 UTC, Saran440 approved these changes
Fuctional Test. LGTM :+1:

2020-10-27 13:05 UTC, AaronHForgeFlow approved these changes

2020-10-28 08:11 UTC, AaronHForgeFlow commented
Nice!:
![purchase_request](https://user-images.githubusercontent.com/19620251/97409188-814c8400-18fd-11eb-87ee-e6841e5bcb37.gif)

2020-10-29 08:37 UTC, HviorForgeFlow commented
/ocabot merge nobump

2020-10-30 08:28 UTC, youring commented
https://github.com/ForgeFlow/purchase-workflow/pull/24
I just added a new icon for eye candy, pls merge. @HviorForgeFlow  Thanks.

2020-11-06 14:29 UTC, AaronHForgeFlow approved these changes

2020-11-06 14:32 UTC, AaronHForgeFlow approved these changes

2020-11-18 13:07 UTC, Saran440 commented
@HviorForgeFlow This PR is ready to merge, Could you merged, please?

2020-11-18 13:22 UTC, HviorForgeFlow commented
/ocabot merge nobump

2020-11-18 13:56 UTC, merged

2020-12-29 09:46 UTC, levkar commented
`track_visibility="onchange",`
should become
`tracking=True,`

occurs many times.